--
-- CDSS decision-tree insert script
-- Tree: "Cây 8: THA + Đái tháo đường týp 2 - Minh"
-- Source: Bảng 18, Bảng 2, Bảng 6, Bảng 7 (Khuyến cáo THA VNHA 2022.pdf)
--
-- This script inserts one decision tree and all its nodes/edges/references
-- into the existing cdss schema. See backups/shared_conventions.txt for the
-- full naming/shape audit this file was brought into line with (extracted
-- from the 5 real seeded trees).
--
-- IDs are generated by gen_random_uuid() (core since PG13). Timestamps are
-- generated by now() at insert time — nothing is hardcoded. Each statement
-- re-resolves the parent id it needs (tree_id by tree_key, node ids by
-- node_key) via a join back to the row inserted by the previous statement.
--
-- Regimen-selection redesign (this pass):
--   The four separate ACEI+CCB / ARB+CCB / ACEI+D / ARB+D INFERENCE nodes
--   had no distinguishing condition, so the engine always took the first
--   in traversal order — there was no real way to choose between them, and
--   picking one arbitrarily would ignore contraindications. Trees 4 and 5
--   (essential-treatment-strategy / optimal-treatment-strategy), which this
--   tree links into, already solve this exact problem: they never resolve
--   ACEI-vs-ARB or a specific drug themselves. They state the class-level
--   option (letter "A" covers both ACEI and ARB) via
--   treatment_preferences.combination_options (see
--   T5_ACTION_FIXED_DOSE_TWO_DRUG_COMBINATION's
--   "combination_options": [["A","C"],["A","D"]]) and hand off to
--   link_target_tree_key = "drug-combination" (Tree 6) for the actual
--   contraindication-based agent pick. Collapsed the four nodes into one
--   T8_INF_REGIMEN_OPTIONS emitting the same combination_options shape,
--   removing the arbitrary always-picks-first behavior and the duplicate
--   fan-out into T8_C_HAS_CV_RISK / T8_C_NO_CV_RISK. Tree 6 itself is not
--   yet seeded (0 rows) — this only makes Tree 8 consistent with Tree 4/5's
--   already-established design, it does not build Tree 6.
--
-- Other fixes applied in an earlier pass (cross-checked against
-- backups/Khuyến cáo THA VNHA 2022.pdf, section 3.7.1, p.34):
--   * The SGLT2i/GLP-1RA trigger condition previously listed six risk
--     factors including invented fields has_atherosclerotic_ckd and
--     has_high_cardiovascular_risk. The actual source text only says
--     "khi có bệnh tim mạch do xơ vữa và/hoặc nguy cơ cao" (atherosclerotic
--     CVD and/or high risk) — no CKD or target-organ-damage mention here.
--     Rebuilt using the established fields has_cardiovascular_disease,
--     has_coronary_artery_disease, has_stroke (ASCVD's components per
--     Bảng 2's own definition) and context.risk.level == "HIGH".
--   * T8_INF_MAINTAIN_REGIMEN uses treatment.status, matching T4's
--     status-flag pattern.
--   * GLOBAL node restructured to the kind/purpose metadata shape used by
--     every real GLOBAL node (was a flat glossary object).
--   * node_source_references: locator/locator_detail were swapped to match
--     convention (locator = full printed caption; locator_detail = terse
--     English usage note). Bảng 2/6/7 given their own reference rows
--     (established convention is one row per distinct source).
--
-- Node type mapping (per legend colors in the source flowchart):
--   green  (Start Node)          -> START
--   yellow (Condition Check)     -> CONDITION
--   blue   (Trigger/Input Node)  -> INFERENCE (applies a context_patch)
--   pink   (Link Node)           -> LINK
--   gray   (glossary/legend box) -> GLOBAL (global_config)
--
-- Safe to run against an empty/staging database. Wrap in a transaction.
-- Use: cmd /c "docker compose exec -T postgres psql -U cdss -d cdss < backups\tree8.sql"
--

BEGIN;
-- ============================================================
-- 1. Tree
-- ============================================================
INSERT INTO public.decision_trees (
        "id",
        "tree_key",
        "name_en",
        "name_vi",
        "created_at",
        "updated_at"
    )
VALUES (
        gen_random_uuid(),
        'hypertension-type-2-diabetes',
        'Hypertension With Type 2 Diabetes',
        'THA + Đái Tháo Đường Týp 2',
        now(),
        now()
    );
-- ============================================================
-- 2. Nodes
-- ============================================================
WITH tree_ctx AS (
    SELECT id AS tree_id
    FROM public.decision_trees
    WHERE tree_key = 'hypertension-type-2-diabetes'
),
node_seed (
    node_key,
    node_type,
    text_en,
    text_vi,
    condition_definition,
    context_patch,
    action_payload,
    global_config,
    link_target_tree_key,
    link_target_node_key,
    display_order
) AS (
    VALUES (
            'T8_START_BP_TARGET_STATUS',
            'START',
            'Tree 3: Blood pressure threshold and treatment target',
            'Cây 3: Ngưỡng huyết áp và đích điều trị',
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            0
        ),
        (
            'T8_C_BELOW_TARGET',
            'CONDITION',
            'SBP < 130 mmHg and DBP < 85 mmHg',
            'HATT < 130 mmHg và HATTr < 85 mmHg',
            '{"all":[{"path":"input.current_clinic_sbp","op":"lt","value":130},{"path":"input.current_clinic_dbp","op":"lt","value":85}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            1
        ),
        (
            'T8_C_ABOVE_TARGET',
            'CONDITION',
            'SBP >= 130 mmHg or DBP >= 85 mmHg',
            'HATT >= 130 mmHg hoặc HATTr >= 85 mmHg',
            '{"any":[{"path":"input.current_clinic_sbp","op":"gte","value":130},{"path":"input.current_clinic_dbp","op":"gte","value":85}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            2
        ),
        (
            'T8_INF_REGIMEN_OPTIONS',
            'INFERENCE',
            'A + C, or A + D (ACE inhibitor/ARB + calcium-channel blocker, or ACE inhibitor/ARB + thiazide-like diuretic)',
            'A + C, hoặc A + D (ƯCMC/CTTA + CKCa, hoặc ƯCMC/CTTA + LT Thiazide-like)',
            NULL::jsonb,
            '{"treatment_preferences":{"combination_options":[["A","C"],["A","D"]]}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            3
        ),
        (
            'T8_C_HAS_CV_RISK',
            'CONDITION',
            'Has atherosclerotic cardiovascular disease (coronary artery disease, stroke, or cardiovascular disease) or high cardiovascular risk',
            'Có bệnh tim mạch do xơ vữa (bệnh mạch vành, đột quỵ, bệnh tim mạch) hoặc nguy cơ tim mạch cao',
            '{"any":[{"path":"input.has_coronary_artery_disease","op":"eq","value":true},{"path":"input.has_stroke","op":"eq","value":true},{"path":"input.has_cardiovascular_disease","op":"eq","value":true},{"path":"context.risk.level","op":"eq","value":"HIGH"}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            4
        ),
        (
            'T8_C_NO_CV_RISK',
            'CONDITION',
            'No atherosclerotic cardiovascular disease and not high cardiovascular risk',
            'Không có bệnh tim mạch do xơ vữa và không thuộc nhóm nguy cơ tim mạch cao',
            '{"not":{"any":[{"path":"input.has_coronary_artery_disease","op":"eq","value":true},{"path":"input.has_stroke","op":"eq","value":true},{"path":"input.has_cardiovascular_disease","op":"eq","value":true},{"path":"context.risk.level","op":"eq","value":"HIGH"}]}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            5
        ),
        (
            'T8_INF_ADD_SGLT2I_GLP1RA',
            'INFERENCE',
            'Add SGLT2i or GLP-1RA',
            'Bổ sung SGLT2i hoặc GLP-1RA',
            NULL::jsonb,
            '{"treatment_preferences":{"additional_drug_classes":["SGLT2_INHIBITOR","GLP1_RECEPTOR_AGONIST"]}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            6
        ),
        (
            'T8_INF_MAINTAIN_REGIMEN',
            'INFERENCE',
            'Maintain current regimen',
            'Duy trì phác đồ',
            NULL::jsonb,
            '{"treatment":{"status":"MAINTAIN_CURRENT_REGIMEN"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            7
        ),
        (
            'T8_LINK_A_ESSENTIAL_TREATMENT_STRATEGY',
            'LINK',
            'Tree 4: Essential treatment strategy',
            'Cây 4: Chiến lược điều trị thiết yếu',
            '{"path":"input.facility_capability","op":"eq","value":"LIMITED_RESOURCES"}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            'essential-treatment-strategy',
            NULL::text,
            8
        ),
        (
            'T8_LINK_A_OPTIMAL_TREATMENT_STRATEGY',
            'LINK',
            'Tree 5: Optimal treatment strategy',
            'Cây 5: Chiến lược điều trị tối ưu',
            '{"path":"input.facility_capability","op":"eq","value":"FULL_RESOURCES"}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            'optimal-treatment-strategy',
            NULL::text,
            9
        ),
        (
            'T8_LINK_B_ESSENTIAL_TREATMENT_STRATEGY',
            'LINK',
            'Tree 4: Essential treatment strategy',
            'Cây 4: Chiến lược điều trị thiết yếu',
            '{"path":"input.facility_capability","op":"eq","value":"LIMITED_RESOURCES"}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            'essential-treatment-strategy',
            NULL::text,
            10
        ),
        (
            'T8_LINK_B_OPTIMAL_TREATMENT_STRATEGY',
            'LINK',
            'Tree 5: Optimal treatment strategy',
            'Cây 5: Chiến lược điều trị tối ưu',
            '{"path":"input.facility_capability","op":"eq","value":"FULL_RESOURCES"}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            'optimal-treatment-strategy',
            NULL::text,
            11
        ),
        (
            'T8_GLOBAL_ABBREVIATION_GLOSSARY',
            'GLOBAL',
            'Abbreviation glossary',
            'Chú giải viết tắt',
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            '{"kind":"ABBREVIATION_GLOSSARY","purpose":"Chú giải các chữ viết tắt nhóm thuốc dùng trong Cây 8 (hệ thống A/B/C/D), theo chú thích Bảng 18.","entries":{"1_A_uc_che_he_RAS":{"label":"A: ức chế hệ RAS","UCMC":"ức chế men chuyển","CTTA":"chẹn thụ thể angiotensin II","ARNI":"chẹn thụ thể Angiotensine-neprisyline"},"4_B_chen_Beta":{"label":"B: chẹn Beta","CB":"chẹn Beta"},"3_C_chen_kenh_Canxi":{"label":"C: chẹn kênh Canxi","CKCa":"chẹn kênh Canxi"},"2_D_loi_tieu":{"label":"D: lợi tiểu","LT":"lợi tiểu"},"6_MRA":{"label":"MRA: thuốc đối kháng thụ thể mineralocorticoid"},"5_SGLT2i":{"label":"SGLT2i: thuốc ức chế đồng vận chuyển Natri-glucose 2"}}}'::jsonb,
            NULL::text,
            NULL::text,
            99
        )
)
INSERT INTO public.decision_nodes (
        "id",
        "tree_id",
        "node_key",
        "node_type",
        "text_en",
        "text_vi",
        "condition_definition",
        "context_patch",
        "action_payload",
        "global_config",
        "link_target_tree_key",
        "link_target_node_key",
        "display_order",
        "created_at",
        "updated_at"
    )
SELECT gen_random_uuid(),
    tree_ctx.tree_id,
    node_seed.node_key,
    node_seed.node_type::node_type,
    node_seed.text_en,
    node_seed.text_vi,
    node_seed.condition_definition,
    node_seed.context_patch,
    node_seed.action_payload,
    node_seed.global_config,
    node_seed.link_target_tree_key,
    node_seed.link_target_node_key,
    node_seed.display_order,
    now(),
    now()
FROM node_seed
    CROSS JOIN tree_ctx;
-- ============================================================
-- 3. Edges
-- ============================================================
WITH tree_ctx AS (
    SELECT id AS tree_id
    FROM public.decision_trees
    WHERE tree_key = 'hypertension-type-2-diabetes'
),
edge_seed (
    from_node_key,
    to_node_key,
    traversal_order
) AS (
    VALUES (
            'T8_START_BP_TARGET_STATUS',
            'T8_C_BELOW_TARGET',
            1
        ),
        (
            'T8_START_BP_TARGET_STATUS',
            'T8_C_ABOVE_TARGET',
            2
        ),
        (
            'T8_C_BELOW_TARGET',
            'T8_LINK_A_ESSENTIAL_TREATMENT_STRATEGY',
            1
        ),
        (
            'T8_C_BELOW_TARGET',
            'T8_LINK_A_OPTIMAL_TREATMENT_STRATEGY',
            2
        ),
        (
            'T8_C_ABOVE_TARGET',
            'T8_INF_REGIMEN_OPTIONS',
            1
        ),
        (
            'T8_INF_REGIMEN_OPTIONS',
            'T8_C_HAS_CV_RISK',
            1
        ),
        (
            'T8_INF_REGIMEN_OPTIONS',
            'T8_C_NO_CV_RISK',
            2
        ),
        (
            'T8_C_HAS_CV_RISK',
            'T8_INF_ADD_SGLT2I_GLP1RA',
            1
        ),
        ('T8_C_NO_CV_RISK', 'T8_INF_MAINTAIN_REGIMEN', 1),
        (
            'T8_INF_ADD_SGLT2I_GLP1RA',
            'T8_LINK_B_ESSENTIAL_TREATMENT_STRATEGY',
            1
        ),
        (
            'T8_INF_ADD_SGLT2I_GLP1RA',
            'T8_LINK_B_OPTIMAL_TREATMENT_STRATEGY',
            2
        ),
        (
            'T8_INF_MAINTAIN_REGIMEN',
            'T8_LINK_B_ESSENTIAL_TREATMENT_STRATEGY',
            1
        ),
        (
            'T8_INF_MAINTAIN_REGIMEN',
            'T8_LINK_B_OPTIMAL_TREATMENT_STRATEGY',
            2
        )
)
INSERT INTO public.decision_edges (
        "id",
        "from_node_id",
        "to_node_id",
        "traversal_order"
    )
SELECT gen_random_uuid(),
    from_node.id,
    to_node.id,
    edge_seed.traversal_order
FROM edge_seed
    CROSS JOIN tree_ctx
    JOIN public.decision_nodes from_node ON from_node.tree_id = tree_ctx.tree_id
    AND from_node.node_key = edge_seed.from_node_key
    JOIN public.decision_nodes to_node ON to_node.tree_id = tree_ctx.tree_id
    AND to_node.node_key = edge_seed.to_node_key;
-- ============================================================
-- 4. Source references
-- ============================================================
WITH tree_ctx AS (
    SELECT id AS tree_id
    FROM public.decision_trees
    WHERE tree_key = 'hypertension-type-2-diabetes'
),
reference_seed (
    node_key,
    source_title,
    section_path,
    locator,
    locator_detail,
    printed_page_numbers,
    pdf_page_numbers,
    reference_note,
    reference_order
) AS (
    VALUES (
            'T8_START_BP_TARGET_STATUS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "1.5", "title": "Phân tầng nguy cơ tim mạch trong tăng huyết áp"}]'::jsonb,
            'Bảng 2. Phân tầng nguy cơ trong tăng huyết áp (2)',
            'Background risk-stratification context carried over from Tree 3, before branching into the diabetes-specific Bảng 18 strategy.',
            ARRAY [11]::smallint [],
            ARRAY [11]::smallint [],
            'Tiếp nối bối cảnh phân tầng nguy cơ từ Cây 3.',
            1
        ),
        (
            'T8_START_BP_TARGET_STATUS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.1", "title": "Ngưỡng huyết áp ban đầu cần điều trị và ranh giới đích điều trị tăng huyết áp"}]'::jsonb,
            'Bảng 6. Ngưỡng huyết áp phòng khám cho điều trị tăng huyết áp theo nhóm tuổi',
            'General clinic-BP treatment threshold by age, inherited from Tree 3 before this diabetes-specific branch.',
            ARRAY [15]::smallint [],
            ARRAY [17]::smallint [],
            'Ngưỡng điều trị chung theo nhóm tuổi, kế thừa từ Cây 3.',
            2
        ),
        (
            'T8_START_BP_TARGET_STATUS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.1", "title": "Ngưỡng huyết áp ban đầu cần điều trị và ranh giới đích điều trị tăng huyết áp"}]'::jsonb,
            'Bảng 7. Mục tiêu huyết áp phòng khám trong điều trị tăng huyết áp theo nhóm tuổi',
            'General clinic-BP treatment target by age, inherited from Tree 3 before this diabetes-specific branch.',
            ARRAY [16]::smallint [],
            ARRAY [18]::smallint [],
            'Đích điều trị chung theo nhóm tuổi, kế thừa từ Cây 3.',
            3
        ),
        (
            'T8_C_BELOW_TARGET',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Clinic BP threshold for hypertension with type 2 diabetes is >=130/85 mmHg; below-target branch.',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Ngưỡng HA phòng khám ở bệnh nhân THA kèm đái tháo đường týp 2 khi >= 130/85 mmHg.',
            1
        ),
        (
            'T8_C_ABOVE_TARGET',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Clinic BP threshold for hypertension with type 2 diabetes is >=130/85 mmHg; at/above-target branch.',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Ngưỡng HA phòng khám ở bệnh nhân THA kèm đái tháo đường týp 2 khi >= 130/85 mmHg.',
            1
        ),
        (
            'T8_INF_REGIMEN_OPTIONS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Combination strategy should include one RAS-inhibitor class (A: ACEI or ARB) and one calcium-channel-blocker or thiazide-like-diuretic class (C or D). Matching Trees 4/5''s own pattern, the specific agent within each class (e.g. ACEI vs ARB) is resolved downstream against contraindications in Tree 6 (drug-combination), not decided here.',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Chiến lược điều trị nên bao gồm một nhóm thuốc ức chế RAS và một nhóm thuốc chẹn kênh canxi hoặc lợi tiểu thiazide-like.',
            1
        ),
        (
            'T8_C_HAS_CV_RISK',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'SGLT2i/GLP-1RA is prioritized when atherosclerotic cardiovascular disease and/or high risk is present.',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Điều trị hạ glucose máu với SGLT2-i hoặc GLP-1 RA được ưu tiên khi có bệnh tim mạch do xơ vữa và/hoặc nguy cơ cao.',
            1
        ),
        (
            'T8_C_NO_CV_RISK',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Complement of the SGLT2i/GLP-1RA trigger: no atherosclerotic cardiovascular disease and not high risk.',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Phần bù của điều kiện kích hoạt SGLT2-i/GLP-1 RA: không có bệnh tim mạch do xơ vữa và không thuộc nhóm nguy cơ cao.',
            1
        ),
        (
            'T8_INF_ADD_SGLT2I_GLP1RA',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Glucose-lowering therapy with SGLT2i or GLP-1RA is prioritized for its demonstrated cardiovascular benefit.',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Điều trị hạ glucose máu với SGLT2-i hoặc GLP-1 RA được ưu tiên với những lợi ích bệnh tim mạch đã được chứng minh.',
            1
        ),
        (
            'T8_INF_MAINTAIN_REGIMEN',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'No indication to add SGLT2i/GLP-1RA: continue the current RAS-inhibitor + CCB/diuretic regimen.',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Không có chỉ định bổ sung SGLT2-i/GLP-1 RA: tiếp tục phác đồ ức chế RAS + CKCa/lợi tiểu hiện tại.',
            1
        ),
        (
            'T8_LINK_A_ESSENTIAL_TREATMENT_STRATEGY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Exit point of the "at target" branch: continue the essential treatment strategy (limited-resource facility).',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Điểm thoát của nhánh "đạt đích": tiếp tục chiến lược điều trị thiết yếu.',
            1
        ),
        (
            'T8_LINK_A_OPTIMAL_TREATMENT_STRATEGY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Exit point of the "at target" branch: continue the optimal treatment strategy (full-resource facility).',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Điểm thoát của nhánh "đạt đích": tiếp tục chiến lược điều trị tối ưu.',
            1
        ),
        (
            'T8_LINK_B_ESSENTIAL_TREATMENT_STRATEGY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Exit point of the "not at target" branch: continue the essential treatment strategy (limited-resource facility).',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Điểm thoát của nhánh "chưa đạt đích": tiếp tục chiến lược điều trị thiết yếu.',
            1
        ),
        (
            'T8_LINK_B_OPTIMAL_TREATMENT_STRATEGY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2)',
            'Exit point of the "not at target" branch: continue the optimal treatment strategy (full-resource facility).',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Điểm thoát của nhánh "chưa đạt đích": tiếp tục chiến lược điều trị tối ưu.',
            1
        ),
        (
            'T8_GLOBAL_ABBREVIATION_GLOSSARY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.7.1", "title": "Tăng huyết áp và Đái tháo đường týp 2"}]'::jsonb,
            'Bảng 18. Chiến lược điều trị tăng huyết áp kèm theo đái tháo đường (2), chú thích',
            'Footnote abbreviation glossary for the drug classes named in Bảng 18.',
            ARRAY [32]::smallint [],
            ARRAY [34]::smallint [],
            'Chú thích Bảng 18: RAS: Hệ renin-angiotensin-aldosterone; GLP-1 RA: thuốc đồng vận thụ thể GLP-1; SGLT2i: Thuốc ức chế SGLT2.',
            1
        )
)
INSERT INTO public.node_source_references (
        "id",
        "node_id",
        "source_title",
        "section_path",
        "locator",
        "locator_detail",
        "printed_page_numbers",
        "pdf_page_numbers",
        "reference_note",
        "reference_order"
    )
SELECT gen_random_uuid(),
    node.id,
    reference_seed.source_title,
    reference_seed.section_path,
    reference_seed.locator,
    reference_seed.locator_detail,
    reference_seed.printed_page_numbers,
    reference_seed.pdf_page_numbers,
    reference_seed.reference_note,
    reference_seed.reference_order
FROM reference_seed
    CROSS JOIN tree_ctx
    JOIN public.decision_nodes node ON node.tree_id = tree_ctx.tree_id
    AND node.node_key = reference_seed.node_key;
COMMIT;
