--
-- CDSS decision-tree insert script
-- Tree: "THA trong thai kỳ - Minh"
-- Source: Bảng 15, Bảng 16 (Khuyến cáo THA VNHA 2022.pdf, Mục 3.6.6, pp.31-32)
--
-- IDs are generated by gen_random_uuid() (core since PG13). Timestamps are
-- generated by now() at insert time — nothing is hardcoded. Each statement
-- re-resolves the parent id it needs (tree_id by tree_key, node ids by
-- node_key) via a join back to the row inserted by the previous statement.
--
-- See backups/shared_conventions.txt for the full naming/shape audit this
-- file was brought into line with (extracted from the 5 real seeded trees).
-- Fixes applied in this pass:
--   * T12_START_PREGNANCY_HTN_SEQUENCE.text_en was showing "Hypertensive
--     Emergency" (a leftover from an unrelated edit) — restored to the
--     tree's actual entry description.
--   * Every ACTION/END node now carries action_type + follow_up_mode +
--     follow_up_required, matching the universal pattern in the 5 real
--     trees' 15 action_payloads (previously the END nodes had none at all).
--   * GLOBAL nodes restructured to the kind/purpose metadata shape used by
--     every real GLOBAL node (was a flat glossary object).
--   * node_source_references: locator/locator_detail were backwards
--     (locator held a short label, locator_detail held the full caption).
--     Fixed to match convention: locator = full printed figure/table
--     caption verbatim; locator_detail = terse English usage note.
--   * Drug names (Methyldopa, Labetalol, Nifedipine, Nicardipine, Esmolol,
--     Hydralazine, Urapidil, Magnesium Sulfate, Nitroglycerin) and disease
--     terms (chronic/gestational hypertension, preeclampsia, eclampsia,
--     HELLP) were verified directly against Bảng 15/16 (PDF pp.31-32) —
--     all confirmed accurate, no changes needed there.
--
-- All previously-applied dialect fixes (path/op/value comparisons,
-- supported operators only, one logical form per condition object,
-- section_path as {"number","title"} objects, smallint[] casts, and the
-- T12_INF_IV_NITROGLYCERIN/T12_INF_MAGNESIUM_SUPPLEMENT ->
-- T12_C_IMMEDIATE_TARGET edges) are preserved. All clinical-content
-- ambiguities already flagged with '-- VERIFY:' are preserved unchanged;
-- none of the naming/shape work above resolves them.
--
-- IMPORTANT — please verify before running in production:
-- The source flowchart image (Miro export) has several spots that were
-- genuinely hard to read at the available resolution. These are flagged
-- inline with '-- VERIFY:' comments and also noted in text_en for the
-- affected nodes. In particular:
--   1. T12_C_PREECLAMPSIA_RISK_FACTOR: exact risk-factor list text
--   2. T12_C_SEVERE_SIGNS -> T12_INF_ECLAMPSIA_CLASSIFICATION /
--      T12_INF_HELLP_SYNDROME_CLASSIFICATION split: the source column
--      boundary between the eclampsia/HELLP criteria box(es) was
--      ambiguous; verify against the original board
--   3. T12_C_TARGET_NOT_MET: exact time threshold text
--   4. T12_C_BP_TARGET_ACHIEVED / T12_C_BP_TARGET_NOT_ACHIEVED: the DBP
--      figure looked identical (85 mmHg) in both boxes in the source
--      image, which is likely an image-quality artifact, not the real
--      clinical criteria — please confirm the actual numbers
--
-- Node type mapping used (confirmed by sampling the legend swatch colors
-- directly, not just by eye):
--   green   Start Node          -> START
--   yellow  Condition Check      -> CONDITION
--   blue    Trigger/Input Node   -> INFERENCE (context_patch)
--   lavender End Node            -> END
--   pink    Link Node            -> LINK (not used in this tree)
--   orange  Action/Output Node   -> ACTION
--   gray    Global Node         -> GLOBAL
--
-- Use: docker compose exec -T postgres psql -U cdss -d cdss -f /path/tree12.sql
--

BEGIN;
-- ============================================================
-- 1. Tree
-- ============================================================
INSERT INTO public.decision_trees (
        "id",
        "tree_key",
        "name_en",
        "name_vi",
        "created_at",
        "updated_at"
    )
VALUES (
        gen_random_uuid(),
        'hypertension-in-pregnancy',
        'Hypertension in Pregnancy',
        'THA trong thai kỳ',
        now(),
        now()
    );
-- ============================================================
-- 2. Nodes
-- ============================================================
WITH tree_ctx AS (
    SELECT id AS tree_id
    FROM public.decision_trees
    WHERE tree_key = 'hypertension-in-pregnancy'
),
node_seed (
    node_key,
    node_type,
    text_en,
    text_vi,
    condition_definition,
    context_patch,
    action_payload,
    global_config,
    link_target_tree_key,
    link_target_node_key,
    display_order
) AS (
    VALUES (
            'T12_START_PREGNANCY_HTN_SEQUENCE',
            'START',
            'Tree 13: Pregnancy sequence / Tree 17: Tree 8 sequence',
            'Cây 13: Trình tự thai kỳ
Cây 17: Trình tự Cây 8',
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            0
        ),
        (
            'T12_C_HOME_BP_HIGH',
            'CONDITION',
            'HATN: SBP>=135 mmHg and DBP>=85 mmHg',
            'HATN
HATT >= 135 mmHg
và
HATTr >= 85 mmHg',
            '{"all": [{"path": "input.home_sbp", "op": "gte", "value": 135}, {"path": "input.home_dbp", "op": "gte", "value": 85}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            1
        ),
        (
            'T12_C_CLINIC_BP_HIGH',
            'CONDITION',
            'HAPK: SBP>=140 mmHg and DBP>=90 mmHg',
            'HAPK
HATT >= 140 mmHg
và
HATTr >= 90 mmHg',
            '{"all": [{"path": "input.current_clinic_sbp", "op": "gte", "value": 140}, {"path": "input.current_clinic_dbp", "op": "gte", "value": 90}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            2
        ),
        (
            'T12_C_CLINIC_BP_NORMAL',
            'CONDITION',
            'HAPK: SBP<140 mmHg and DBP<90 mmHg',
            'HAPK
HATT < 140 mmHg
và
HATTr < 90 mmHg',
            '{"all": [{"path": "input.current_clinic_sbp", "op": "lt", "value": 140}, {"path": "input.current_clinic_dbp", "op": "lt", "value": 90}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            3
        ),
        (
            'T12_END_FOLLOW_UP_MONITOR',
            'END',
            'Follow-up / monitor',
            'Theo dõi',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "CONTINUE_MONITORING", "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            4
        ),
        (
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            'ACTION',
            'Determine type of hypertensive disorder of pregnancy',
            'Xác định kiểu THA trong thai kỳ',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "CLASSIFY_PREGNANCY_HYPERTENSION_TYPE", "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            5
        ),
        (
            'T12_C_CHRONIC_HTN',
            'CONDITION',
            'Chronic HTN before pregnancy/before week 20, persisting >6 weeks postpartum with proteinuria',
            'THA trước khi mang thai hoặc trước tuần 20, tồn tại > 6 tuần sau sinh với protein niệu.',
            '{"all": [{"any": [{"path": "input.has_pre_pregnancy_hypertension", "op": "eq", "value": true}, {"path": "input.has_hypertension_before_week_20", "op": "eq", "value": true}]}, {"all": [{"path": "input.weeks_persisting_postpartum", "op": "gt", "value": 6}, {"path": "input.has_proteinuria", "op": "eq", "value": true}]}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            6
        ),
        (
            'T12_END_PRE_EXISTING_HTN',
            'END',
            'Pre-existing (chronic) hypertension',
            'THA từ trước',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "PRE_EXISTING_HYPERTENSION_DIAGNOSIS", "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            7
        ),
        (
            'T12_C_GESTATIONAL_HTN',
            'CONDITION',
            'Gestational HTN after week 20, resolving <6 weeks postpartum',
            'THA sau tuần 20, kéo dài < 6 tuần sau sinh',
            '{"all": [{"path": "input.has_hypertension_after_week_20", "op": "eq", "value": true}, {"path": "input.weeks_resolved_postpartum", "op": "lt", "value": 6}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            8
        ),
        (
            'T12_INF_GESTATIONAL_HTN_CLASSIFICATION',
            'INFERENCE',
            'Gestational hypertension',
            'Thai kỳ',
            NULL::jsonb,
            '{"diagnosis": {"pregnancy_hypertension_type": "GESTATIONAL_HYPERTENSION"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            9
        ),
        (
            'T12_C_PREECLAMPSIA_PROTEINURIA',
            'CONDITION',
            'or gestational HTN with proteinuria >300mg/24h or ACR>=30mg/mmol',
            'hoặc THA thai kỳ có Protein niệu >300mg/24h
hoặc ACR >= 30 mg/mmol',
            '{"any": [{"path": "input.proteinuria_24h_mg", "op": "gt", "value": 300}, {"path": "input.acr_mg_mmol", "op": "gte", "value": 30}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            10
        ),
        -- VERIFY: T12_C_PREECLAMPSIA_RISK_FACTOR exact risk-factor list text (source image partly illegible)
        (
            'T12_C_PREECLAMPSIA_RISK_FACTOR',
            'CONDITION',
            'or has >=1 risk factor (prior gestational HTN, diabetes, chronic kidney disease, autoimmune disease, etc.) [text partly illegible in source image]',
            'hoặc có 1 trong các Yếu Tố Nguy Cơ:
THA trong lần thai trước đó / đái tháo đường / bệnh thận mạn / thai lần đầu hoặc nhiều lần / bệnh tự miễn',
            '{"any": [{"path": "input.has_prior_gestational_hypertension", "op": "eq", "value": true}, {"path": "input.has_diabetes", "op": "eq", "value": true}, {"path": "input.has_ckd", "op": "eq", "value": true}, {"path": "input.has_autoimmune_disease", "op": "eq", "value": true}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            11
        ),
        (
            'T12_INF_PREECLAMPSIA_CLASSIFICATION',
            'INFERENCE',
            'Preeclampsia',
            'Tiền sản giật',
            NULL::jsonb,
            '{"diagnosis": {"pregnancy_hypertension_type": "PREECLAMPSIA"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            12
        ),
        -- VERIFY: T12_C_SEVERE_SIGNS / T12_INF_ECLAMPSIA_CLASSIFICATION / T12_INF_HELLP_SYNDROME_CLASSIFICATION column boundary uncertain in source image
        (
            'T12_C_SEVERE_SIGNS',
            'CONDITION',
            'Severe features: seizure, severe headache, visual disturbance, epigastric pain, hemolysis, elevated liver enzymes, low platelets [column boundary in source image uncertain — see note]',
            'Tán huyết, tăng men gan, giảm tiểu cầu (Hemolysis, elevated liver enzymes, low platelets); có thể kèm co giật, đau đầu dữ dội, rối loạn thị giác, đau thượng vị',
            '{"any": [{"path": "input.has_seizure", "op": "eq", "value": true}, {"path": "input.has_severe_headache", "op": "eq", "value": true}, {"path": "input.has_visual_disturbance", "op": "eq", "value": true}, {"path": "input.has_epigastric_pain", "op": "eq", "value": true}, {"path": "input.has_hemolysis", "op": "eq", "value": true}, {"path": "input.has_elevated_liver_enzymes", "op": "eq", "value": true}, {"path": "input.has_low_platelets", "op": "eq", "value": true}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            13
        ),
        (
            'T12_INF_ECLAMPSIA_CLASSIFICATION',
            'INFERENCE',
            'Eclampsia',
            'Sản giật',
            NULL::jsonb,
            '{"diagnosis": {"pregnancy_hypertension_type": "ECLAMPSIA"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            14
        ),
        (
            'T12_INF_HELLP_SYNDROME_CLASSIFICATION',
            'INFERENCE',
            'HELLP syndrome',
            'Hội chứng HELLP',
            NULL::jsonb,
            '{"diagnosis": {"pregnancy_hypertension_type": "HELLP_SYNDROME"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            15
        ),
        (
            'T12_C_BP_MILD_MODERATE',
            'CONDITION',
            'SBP 140-159 mmHg OR DBP 90-109 mmHg',
            'HATT 140-159 mmHg
HOẶC
HATTr 90-109 mmHg',
            '{"any": [{"all": [{"path": "input.current_clinic_sbp", "op": "gte", "value": 140}, {"path": "input.current_clinic_sbp", "op": "lte", "value": 159}]}, {"all": [{"path": "input.current_clinic_dbp", "op": "gte", "value": 90}, {"path": "input.current_clinic_dbp", "op": "lte", "value": 109}]}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            16
        ),
        (
            'T12_C_BP_SEVERE',
            'CONDITION',
            'SBP>=160 mmHg OR DBP>=110 mmHg',
            'HATT >= 160 mmHg
HOẶC
HATTr >= 110 mmHg',
            '{"any": [{"path": "input.current_clinic_sbp", "op": "gte", "value": 160}, {"path": "input.current_clinic_dbp", "op": "gte", "value": 110}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            17
        ),
        (
            'T12_INF_MILD_MODERATE_SEVERITY',
            'INFERENCE',
            'Mild-moderate',
            'Tính nhẹ - trung bình',
            NULL::jsonb,
            '{"treatment": {"severity": "MILD_MODERATE"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            18
        ),
        (
            'T12_INF_SEVERE_SEVERITY',
            'INFERENCE',
            'Severe hypertension',
            'THA nặng',
            NULL::jsonb,
            '{"treatment": {"severity": "SEVERE"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            19
        ),
        (
            'T12_INF_METHYLDOPA',
            'INFERENCE',
            '(Central alpha-2 agonist) Methyldopa',
            '(Chủ vận chọn lọc alpha-2 giao cảm)
Methyldopa',
            NULL::jsonb,
            '{"treatment_preferences": {"preferred_drug": "Methyldopa", "drug_class": "CENTRAL_ALPHA2_AGONIST"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            20
        ),
        (
            'T12_INF_LABETALOL_ORAL',
            'INFERENCE',
            '(Beta blocker) Labetalol',
            '(Chẹn Beta)
Labetalol',
            NULL::jsonb,
            '{"treatment_preferences": {"preferred_drug": "Labetalol", "drug_class": "BETA_BLOCKER"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            21
        ),
        (
            'T12_INF_NIFEDIPINE_OR_NICARDIPINE',
            'INFERENCE',
            '(Dihydropyridine CCB) Nifedipine (avoid capsule form) or Nicardipine',
            '(CKCa - Dihydropyridine)
Nifedipine [trừ viên dạng nang]
hoặc
Nicardipine',
            NULL::jsonb,
            '{"treatment_preferences": {"drug_options": ["Nifedipine (trừ viên dạng nang)", "Nicardipine"], "drug_class": "DIHYDROPYRIDINE_CCB"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            22
        ),
        (
            'T12_INF_ABSOLUTE_CONTRAINDICATIONS',
            'INFERENCE',
            'Absolute contraindication: A (ACEI, ARB), ARNI',
            'Chống chỉ định tuyệt đối:
A (ƯCMC, CTTA)
ARNI',
            NULL::jsonb,
            '{"treatment": {"absolute_contraindications": ["ƯCMC (ức chế men chuyển)", "CTTA (chẹn thụ thể angiotensin II)", "ARNI"]}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            23
        ),
        (
            'T12_INF_SEVERE_DRUG_OPTIONS',
            'INFERENCE',
            'Methyldopa oral, or Nifedipine/Nicardipine, or IV Labetalol/Nicardipine, or Esmolol, Hydralazine, Urapidil',
            'Methyldopa uống
hoặc (CKCa-Dihydropyridine) Nifedipine [trừ viên dạng nang] hoặc Nicardipine
hoặc Labetalol tĩnh mạch
hoặc Nicardipine tĩnh mạch
hoặc Esmolol (Chẹn Beta)
hoặc Hydralazine (Giãn mạch)
hoặc Urapidil',
            NULL::jsonb,
            '{"treatment_preferences": {"drug_options": ["Methyldopa (uống)", "Nifedipine (uống, trừ viên dạng nang)", "Nicardipine (uống hoặc TM)", "Labetalol (TM)", "Esmolol (chẹn Beta)", "Hydralazine (giãn mạch)", "Urapidil"]}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            24
        ),
        (
            'T12_C_HYPERTENSIVE_CRISIS',
            'CONDITION',
            'Hypertensive crisis',
            'Liên cơn THA',
            '{"path": "input.has_hypertensive_crisis", "op": "eq", "value": true}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            25
        ),
        (
            'T12_C_PULMONARY_EDEMA',
            'CONDITION',
            'Pulmonary edema',
            'Phù phổi',
            '{"path": "input.has_pulmonary_edema", "op": "eq", "value": true}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            26
        ),
        (
            'T12_INF_IV_NITROGLYCERIN',
            'INFERENCE',
            'IV nitroglycerin infusion',
            'Truyền Nitroglycerin tĩnh mạch',
            NULL::jsonb,
            '{"treatment_preferences": {"preferred_drug": "Nitroglycerin", "route": "IV_INFUSION"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            27
        ),
        (
            'T12_INF_MAGNESIUM_SUPPLEMENT',
            'INFERENCE',
            'Add magnesium',
            'Bổ sung magie',
            NULL::jsonb,
            '{"treatment_preferences": {"add_on_drug": "Magnesium Sulfate"}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            28
        ),
        (
            'T12_INF_LABETALOL_MGSO4',
            'INFERENCE',
            'Labetalol + Magnesium Sulfate',
            'Labetalol (Chẹn Beta) +
Magnesium Sulfate',
            NULL::jsonb,
            '{"treatment_preferences": {"drug_options": ["Labetalol", "Magnesium Sulfate"]}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            29
        ),
        (
            'T12_INF_NICARDIPINE_MGSO4',
            'INFERENCE',
            'Nicardipine + Magnesium Sulfate',
            'Nicardipine (CKCa) +
Magnesium Sulfate',
            NULL::jsonb,
            '{"treatment_preferences": {"drug_options": ["Nicardipine", "Magnesium Sulfate"]}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            30
        ),
        (
            'T12_C_IMMEDIATE_TARGET',
            'CONDITION',
            'Immediate treatment target: SBP<160 mmHg and DBP<105 mmHg',
            'Đích điều trị
Ngay lập tức hạ HA
HATT < 160 mmHg
và
HATTr < 105 mmHg',
            '{"all": [{"path": "input.current_clinic_sbp", "op": "lt", "value": 160}, {"path": "input.current_clinic_dbp", "op": "lt", "value": 105}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            31
        ),
        -- VERIFY: T12_C_TARGET_NOT_MET exact time threshold text illegible in source image
        (
            'T12_C_TARGET_NOT_MET',
            'CONDITION',
            'If target not reached, or visual disturbance / coagulopathy present [exact timing text illegible in source image]',
            'Nếu không đạt được đích điều trị,
hoặc có rối loạn thị giác, rối loạn đông cầm máu',
            '{"any": [{"path": "input.is_treatment_target_not_achieved", "op": "eq", "value": true}, {"path": "input.has_visual_disturbance", "op": "eq", "value": true}, {"path": "input.has_coagulopathy", "op": "eq", "value": true}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            32
        ),
        (
            'T12_END_EMERGENCY_DELIVERY',
            'END',
            'Emergency delivery, terminate pregnancy',
            'Lấy thai cấp cứu, chấm dứt thai kỳ',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "EMERGENCY_DELIVERY", "follow_up_mode": "IMMEDIATE", "follow_up_required": false}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            33
        ),
        (
            'T12_ACTION_MONITOR_PREGNANCY_POSTPARTUM',
            'ACTION',
            'Monitor pregnancy status and postpartum',
            'Theo dõi tình trạng thai kỳ và hậu sản',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "MONITOR_PREGNANCY_AND_POSTPARTUM", "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            34
        ),
        (
            'T12_C_CURRENTLY_PREGNANT',
            'CONDITION',
            'Currently pregnant',
            'Đang mang thai',
            '{"path": "input.is_pregnant", "op": "eq", "value": true}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            35
        ),
        (
            'T12_C_POSTPARTUM',
            'CONDITION',
            'Postpartum',
            'Sau sinh',
            '{"path": "input.is_postpartum", "op": "eq", "value": true}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            36
        ),
        (
            'T12_C_HIGH_PREECLAMPSIA_RISK',
            'CONDITION',
            'High risk of preeclampsia',
            'Nguy cơ tiền sản giật cao',
            '{"path": "input.has_high_preeclampsia_risk", "op": "eq", "value": true}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            37
        ),
        (
            'T12_END_ASPIRIN_PROPHYLAXIS',
            'END',
            'Aspirin 75-162mg from week 12-36',
            'Aspirin 75-162 mg từ tuần 12-36',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "ASPIRIN_PROPHYLAXIS", "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            38
        ),
        -- VERIFY: T12_C_BP_TARGET_ACHIEVED exact DBP figure uncertain in source image (looked identical to the not-achieved box)
        (
            'T12_C_BP_TARGET_ACHIEVED',
            'CONDITION',
            'BP target achieved: SBP 110-140 mmHg and DBP ~85 mmHg [exact DBP figure uncertain in source image]',
            'HA Đạt Đích Điều Trị
HATT 110 - 140 mmHg
và
HATTr 85 mmHg',
            '{"all": [{"path": "input.current_clinic_sbp", "op": "gte", "value": 110}, {"path": "input.current_clinic_sbp", "op": "lte", "value": 140}, {"path": "input.current_clinic_dbp", "op": "eq", "value": 85}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            39
        ),
        (
            'T12_END_MAINTAIN_REGIMEN_PREGNANT',
            'END',
            'Maintain regimen',
            'Duy trì phác đồ',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "MAINTAIN_CURRENT_REGIMEN", "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            40
        ),
        -- VERIFY: T12_C_BP_TARGET_NOT_ACHIEVED criteria text partly illegible in source image, appeared identical to
        -- T12_C_BP_TARGET_ACHIEVED; defined here as that condition's exact negation pending confirmation against the
        -- original board (a CONDITION node cannot carry a placeholder, non-boolean note as its condition_definition)
        (
            'T12_C_BP_TARGET_NOT_ACHIEVED',
            'CONDITION',
            'BP target not achieved [criteria text partly illegible in source image, appears identical range to the achieved box]',
            'HA Không Đạt Đích Điều Trị
HATT 110 - 140 mmHg
và
HATTr 85 mmHg',
            '{"not": {"all": [{"path": "input.current_clinic_sbp", "op": "gte", "value": 110}, {"path": "input.current_clinic_sbp", "op": "lte", "value": 140}, {"path": "input.current_clinic_dbp", "op": "eq", "value": 85}]}}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            41
        ),
        (
            'T12_END_REFER_OBGYN',
            'END',
            'Refer to OB specialist',
            'Chuyển chuyên khoa Sản',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "REFER_TO_OBGYN_SPECIALIST", "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            42
        ),
        (
            'T12_C_BREASTFEEDING',
            'CONDITION',
            'Currently breastfeeding',
            'Đang cho con bú',
            '{"path": "input.is_breastfeeding", "op": "eq", "value": true}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            43
        ),
        (
            'T12_C_BP_STILL_HIGH',
            'CONDITION',
            'BP still high: SBP>=140mmHg or DBP>=90mmHg',
            'HA còn cao
HATT >= 140 mmHg
hoặc
HATTr >= 90 mmHg',
            '{"any": [{"path": "input.current_clinic_sbp", "op": "gte", "value": 140}, {"path": "input.current_clinic_dbp", "op": "gte", "value": 90}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            44
        ),
        (
            'T12_C_BP_NOT_HIGH',
            'CONDITION',
            'BP no longer high: SBP<140mmHg and DBP<90mmHg',
            'HA không còn cao
HATT < 140 mmHg
và
HATTr < 90 mmHg',
            '{"all": [{"path": "input.current_clinic_sbp", "op": "lt", "value": 140}, {"path": "input.current_clinic_dbp", "op": "lt", "value": 90}]}'::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            45
        ),
        (
            'T12_ACTION_POSTPARTUM_CONTRAINDICATIONS',
            'ACTION',
            'Mandatory contraindications while breastfeeding / BP still high',
            'Chống chỉ định bắt buộc: Nicardipine
Tránh Atenolol, Propranolol, Nifedipine
Ưu tiên dùng Methyldopa / CKCa kéo dài',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "POSTPARTUM_DRUG_CONTRAINDICATIONS", "contraindicated_drugs": ["Nicardipine"], "drugs_to_avoid": ["Atenolol", "Propranolol", "Nifedipine"], "preferred_drugs": ["Methyldopa", "CKCa tác dụng kéo dài"], "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            46
        ),
        (
            'T12_END_MAINTAIN_REGIMEN_POSTPARTUM',
            'END',
            'Maintain regimen',
            'Duy trì phác đồ',
            NULL::jsonb,
            NULL::jsonb,
            '{"action_type": "MAINTAIN_CURRENT_REGIMEN", "follow_up_mode": "NEW_ENCOUNTER", "follow_up_required": true}'::jsonb,
            NULL::jsonb,
            NULL::text,
            NULL::text,
            47
        ),
        (
            'T12_GLOBAL_ABBREVIATION_GLOSSARY',
            'GLOBAL',
            'Abbreviation glossary',
            'Chú giải viết tắt',
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            '{"kind": "ABBREVIATION_GLOSSARY", "purpose": "Chú giải các chữ viết tắt nhóm thuốc dùng trong Cây 12.", "entries": {"1_A_uc_che_he_RAS": {"label": "A: ức chế hệ RAS", "UCMC": "ức chế men chuyển", "CTTA": "chẹn thụ thể angiotensin II", "ARNI": "chẹn thụ thể Angiotensine-neprisyline"}, "4_B_chen_Beta": {"label": "B: chẹn Beta", "CB": "chẹn Beta"}, "3_C_chen_kenh_Canxi": {"label": "C: chẹn kênh Canxi", "CKCa": "chẹn kênh Canxi"}, "2_D_loi_tieu": {"label": "D: lợi tiểu", "LT": "lợi tiểu"}, "6_MRA": {"label": "MRA: thuốc đối kháng thụ thể mineralocorticoid"}, "5_SGLT2i": {"label": "SGLT2i: dapagliflozin / empagliflozin"}}}'::jsonb,
            NULL::text,
            NULL::text,
            98
        ),
        (
            'T12_GLOBAL_PREGNANCY_DRUG_CONTRAINDICATIONS',
            'GLOBAL',
            'Drug contraindications in pregnancy',
            'Chống chỉ định thuốc trong thai kỳ',
            NULL::jsonb,
            NULL::jsonb,
            NULL::jsonb,
            '{"kind": "OVERRIDE_NOTE", "purpose": "Chống chỉ định thuốc bắt buộc trong thai kỳ, áp dụng cho mọi lựa chọn thuốc hạ áp trong Cây 12.", "details": {"chong_chi_dinh_uc_che_he_RAS": {"label": "Chống chỉ định các thuốc ức chế hệ RAS gồm", "items": ["Ức chế men chuyển (ƯCMC)", "Chẹn thụ thể Angiotensin II (CTTA)", "Ức chế renin trực tiếp", "thuốc kháng thụ thể Mineralocorticoid (MRA)"]}, "chong_chi_dinh_natri_nitroprusside": {"label": "Chống chỉ định Natri Nitroprusside (Giãn mạch)", "ly_do": "do nguy cơ nhiễm độc xyanua thai nhi"}}}'::jsonb,
            NULL::text,
            NULL::text,
            99
        )
)
INSERT INTO public.decision_nodes (
        "id",
        "tree_id",
        "node_key",
        "node_type",
        "text_en",
        "text_vi",
        "condition_definition",
        "context_patch",
        "action_payload",
        "global_config",
        "link_target_tree_key",
        "link_target_node_key",
        "display_order",
        "created_at",
        "updated_at"
    )
SELECT gen_random_uuid(),
    tree_ctx.tree_id,
    node_seed.node_key,
    node_seed.node_type::node_type,
    node_seed.text_en,
    node_seed.text_vi,
    node_seed.condition_definition,
    node_seed.context_patch,
    node_seed.action_payload,
    node_seed.global_config,
    node_seed.link_target_tree_key,
    node_seed.link_target_node_key,
    node_seed.display_order,
    now(),
    now()
FROM node_seed
    CROSS JOIN tree_ctx;
-- ============================================================
-- 3. Edges
-- ============================================================
WITH tree_ctx AS (
    SELECT id AS tree_id
    FROM public.decision_trees
    WHERE tree_key = 'hypertension-in-pregnancy'
),
edge_seed (
    from_node_key,
    to_node_key,
    traversal_order
) AS (
    VALUES (
            'T12_START_PREGNANCY_HTN_SEQUENCE',
            'T12_C_HOME_BP_HIGH',
            1
        ),
        (
            'T12_START_PREGNANCY_HTN_SEQUENCE',
            'T12_C_CLINIC_BP_HIGH',
            2
        ),
        (
            'T12_START_PREGNANCY_HTN_SEQUENCE',
            'T12_C_CLINIC_BP_NORMAL',
            3
        ),
        (
            'T12_C_CLINIC_BP_NORMAL',
            'T12_END_FOLLOW_UP_MONITOR',
            1
        ),
        (
            'T12_C_HOME_BP_HIGH',
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            1
        ),
        (
            'T12_C_CLINIC_BP_HIGH',
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            1
        ),
        (
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            'T12_C_CHRONIC_HTN',
            1
        ),
        (
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            'T12_C_GESTATIONAL_HTN',
            2
        ),
        (
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            'T12_C_PREECLAMPSIA_PROTEINURIA',
            3
        ),
        (
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            'T12_C_PREECLAMPSIA_RISK_FACTOR',
            4
        ),
        (
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            'T12_C_SEVERE_SIGNS',
            5
        ),
        (
            'T12_C_CHRONIC_HTN',
            'T12_END_PRE_EXISTING_HTN',
            1
        ),
        (
            'T12_C_GESTATIONAL_HTN',
            'T12_INF_GESTATIONAL_HTN_CLASSIFICATION',
            1
        ),
        (
            'T12_C_PREECLAMPSIA_PROTEINURIA',
            'T12_INF_PREECLAMPSIA_CLASSIFICATION',
            1
        ),
        (
            'T12_C_PREECLAMPSIA_RISK_FACTOR',
            'T12_INF_PREECLAMPSIA_CLASSIFICATION',
            1
        ),
        (
            'T12_C_SEVERE_SIGNS',
            'T12_INF_ECLAMPSIA_CLASSIFICATION',
            1
        ),
        (
            'T12_C_SEVERE_SIGNS',
            'T12_INF_HELLP_SYNDROME_CLASSIFICATION',
            2
        ),
        (
            'T12_INF_GESTATIONAL_HTN_CLASSIFICATION',
            'T12_C_BP_MILD_MODERATE',
            1
        ),
        (
            'T12_INF_GESTATIONAL_HTN_CLASSIFICATION',
            'T12_C_BP_SEVERE',
            2
        ),
        (
            'T12_INF_PREECLAMPSIA_CLASSIFICATION',
            'T12_C_BP_MILD_MODERATE',
            1
        ),
        (
            'T12_INF_PREECLAMPSIA_CLASSIFICATION',
            'T12_C_BP_SEVERE',
            2
        ),
        (
            'T12_C_BP_MILD_MODERATE',
            'T12_INF_MILD_MODERATE_SEVERITY',
            1
        ),
        ('T12_C_BP_SEVERE', 'T12_INF_SEVERE_SEVERITY', 1),
        (
            'T12_INF_MILD_MODERATE_SEVERITY',
            'T12_INF_METHYLDOPA',
            1
        ),
        (
            'T12_INF_MILD_MODERATE_SEVERITY',
            'T12_INF_LABETALOL_ORAL',
            2
        ),
        (
            'T12_INF_MILD_MODERATE_SEVERITY',
            'T12_INF_NIFEDIPINE_OR_NICARDIPINE',
            3
        ),
        (
            'T12_INF_METHYLDOPA',
            'T12_INF_ABSOLUTE_CONTRAINDICATIONS',
            1
        ),
        (
            'T12_INF_LABETALOL_ORAL',
            'T12_INF_ABSOLUTE_CONTRAINDICATIONS',
            1
        ),
        (
            'T12_INF_NIFEDIPINE_OR_NICARDIPINE',
            'T12_INF_ABSOLUTE_CONTRAINDICATIONS',
            1
        ),
        (
            'T12_INF_SEVERE_SEVERITY',
            'T12_INF_SEVERE_DRUG_OPTIONS',
            1
        ),
        (
            'T12_INF_SEVERE_DRUG_OPTIONS',
            'T12_C_HYPERTENSIVE_CRISIS',
            1
        ),
        (
            'T12_INF_SEVERE_DRUG_OPTIONS',
            'T12_C_PULMONARY_EDEMA',
            2
        ),
        (
            'T12_C_HYPERTENSIVE_CRISIS',
            'T12_INF_IV_NITROGLYCERIN',
            1
        ),
        (
            'T12_C_PULMONARY_EDEMA',
            'T12_INF_MAGNESIUM_SUPPLEMENT',
            1
        ),
        (
            'T12_INF_ECLAMPSIA_CLASSIFICATION',
            'T12_INF_LABETALOL_MGSO4',
            1
        ),
        (
            'T12_INF_ECLAMPSIA_CLASSIFICATION',
            'T12_INF_NICARDIPINE_MGSO4',
            2
        ),
        (
            'T12_INF_HELLP_SYNDROME_CLASSIFICATION',
            'T12_INF_LABETALOL_MGSO4',
            1
        ),
        (
            'T12_INF_HELLP_SYNDROME_CLASSIFICATION',
            'T12_INF_NICARDIPINE_MGSO4',
            2
        ),
        (
            'T12_INF_LABETALOL_MGSO4',
            'T12_C_IMMEDIATE_TARGET',
            1
        ),
        (
            'T12_INF_NICARDIPINE_MGSO4',
            'T12_C_IMMEDIATE_TARGET',
            1
        ),
        (
            'T12_INF_IV_NITROGLYCERIN',
            'T12_C_IMMEDIATE_TARGET',
            1
        ),
        (
            'T12_INF_MAGNESIUM_SUPPLEMENT',
            'T12_C_IMMEDIATE_TARGET',
            1
        ),
        (
            'T12_C_IMMEDIATE_TARGET',
            'T12_C_TARGET_NOT_MET',
            1
        ),
        (
            'T12_C_TARGET_NOT_MET',
            'T12_END_EMERGENCY_DELIVERY',
            1
        ),
        (
            'T12_INF_ABSOLUTE_CONTRAINDICATIONS',
            'T12_ACTION_MONITOR_PREGNANCY_POSTPARTUM',
            1
        ),
        (
            'T12_ACTION_MONITOR_PREGNANCY_POSTPARTUM',
            'T12_C_CURRENTLY_PREGNANT',
            1
        ),
        (
            'T12_ACTION_MONITOR_PREGNANCY_POSTPARTUM',
            'T12_C_POSTPARTUM',
            2
        ),
        (
            'T12_C_CURRENTLY_PREGNANT',
            'T12_C_HIGH_PREECLAMPSIA_RISK',
            1
        ),
        (
            'T12_C_CURRENTLY_PREGNANT',
            'T12_C_BP_TARGET_ACHIEVED',
            2
        ),
        (
            'T12_C_CURRENTLY_PREGNANT',
            'T12_C_BP_TARGET_NOT_ACHIEVED',
            3
        ),
        (
            'T12_C_HIGH_PREECLAMPSIA_RISK',
            'T12_END_ASPIRIN_PROPHYLAXIS',
            1
        ),
        (
            'T12_C_BP_TARGET_ACHIEVED',
            'T12_END_MAINTAIN_REGIMEN_PREGNANT',
            1
        ),
        (
            'T12_C_BP_TARGET_NOT_ACHIEVED',
            'T12_END_REFER_OBGYN',
            1
        ),
        ('T12_C_POSTPARTUM', 'T12_C_BREASTFEEDING', 1),
        ('T12_C_POSTPARTUM', 'T12_C_BP_STILL_HIGH', 2),
        ('T12_C_POSTPARTUM', 'T12_C_BP_NOT_HIGH', 3),
        (
            'T12_C_BREASTFEEDING',
            'T12_ACTION_POSTPARTUM_CONTRAINDICATIONS',
            1
        ),
        (
            'T12_C_BP_STILL_HIGH',
            'T12_ACTION_POSTPARTUM_CONTRAINDICATIONS',
            1
        ),
        (
            'T12_C_BP_NOT_HIGH',
            'T12_END_MAINTAIN_REGIMEN_POSTPARTUM',
            1
        ),
        (
            'T12_ACTION_POSTPARTUM_CONTRAINDICATIONS',
            'T12_END_MAINTAIN_REGIMEN_POSTPARTUM',
            1
        )
)
INSERT INTO public.decision_edges (
        "id",
        "from_node_id",
        "to_node_id",
        "traversal_order"
    )
SELECT gen_random_uuid(),
    from_node.id,
    to_node.id,
    edge_seed.traversal_order
FROM edge_seed
    CROSS JOIN tree_ctx
    JOIN public.decision_nodes from_node ON from_node.tree_id = tree_ctx.tree_id
    AND from_node.node_key = edge_seed.from_node_key
    JOIN public.decision_nodes to_node ON to_node.tree_id = tree_ctx.tree_id
    AND to_node.node_key = edge_seed.to_node_key;
-- ============================================================
-- 4. Source references
-- ============================================================
WITH tree_ctx AS (
    SELECT id AS tree_id
    FROM public.decision_trees
    WHERE tree_key = 'hypertension-in-pregnancy'
),
reference_seed (
    node_key,
    source_title,
    section_path,
    locator,
    locator_detail,
    printed_page_numbers,
    pdf_page_numbers,
    reference_note,
    reference_order
) AS (
    VALUES (
            'T12_START_PREGNANCY_HTN_SEQUENCE',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Mục 3.6.6. Tăng huyết áp trong thai kỳ',
            'Entry point of the pregnancy-hypertension sequence.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Điểm vào của trình tự THA trong thai kỳ, theo Mục 3.6.6.',
            1
        ),
        (
            'T12_ACTION_CLASSIFY_HTN_TYPE',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Classifies into the 5 categories of Bảng 15: pre-existing, gestational, preeclampsia, eclampsia, HELLP syndrome.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Phân loại theo 5 nhóm của Bảng 15: THA từ trước, THA thai kỳ, Tiền sản giật, Sản giật, Hội chứng HELLP.',
            1
        ),
        (
            'T12_END_FOLLOW_UP_MONITOR',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'BP below the 140/90 mmHg (clinic) / 135/85 mmHg (home) treatment threshold does not require drug therapy; continue monitoring.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'HA dưới ngưỡng 140/90 mmHg (phòng khám) / 135/85 mmHg (tại nhà) không cần điều trị thuốc; tiếp tục theo dõi.',
            1
        ),
        (
            'T12_C_CHRONIC_HTN',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Pre-existing hypertension: present before pregnancy or before week 20, persisting >6 weeks postpartum with proteinuria.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'THA có trước khi mang thai hoặc trước tuần lễ thứ 20 của thai kỳ và tồn tại > 6 tuần sau sinh với protein niệu.',
            1
        ),
        (
            'T12_END_PRE_EXISTING_HTN',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Terminal classification: pre-existing (chronic) hypertension.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Phân loại kết thúc "THA từ trước" của Bảng 15.',
            1
        ),
        (
            'T12_C_GESTATIONAL_HTN',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Gestational hypertension: onset after week 20, resolving within 6 weeks postpartum.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'THA khởi phát sau tuần thứ 20 của thai kỳ, và kéo dài < 6 tuần sau sinh.',
            1
        ),
        (
            'T12_INF_GESTATIONAL_HTN_CLASSIFICATION',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Classification label: gestational hypertension.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Nhãn phân loại "THA trong thai kỳ" (gestational hypertension) của Bảng 15.',
            1
        ),
        (
            'T12_C_PREECLAMPSIA_PROTEINURIA',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Preeclampsia: gestational hypertension with proteinuria >300mg/24h or ACR >=30 mg/mmol [265 mg/g].',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'THA thai kỳ và có protein niệu (>300 mg/24h hoặc tỷ albumin/creatinine niệu (ACR) >30 mg/mmol [265 mg/g]).',
            1
        ),
        (
            'T12_C_PREECLAMPSIA_RISK_FACTOR',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Preeclampsia risk factors: prior hypertension, prior gestational hypertension, diabetes, kidney disease, nulliparity/multiparity, autoimmune disease (SLE).',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Các yếu tố nguy cơ: THA từ trước, THA trong lần thai kỳ trước, đái tháo đường, bệnh thận, thai lần đầu hay nhiều lần, và bệnh tự miễn (SLE).',
            1
        ),
        (
            'T12_INF_PREECLAMPSIA_CLASSIFICATION',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Classification label: preeclampsia.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Nhãn phân loại "Tiền sản giật" (preeclampsia) của Bảng 15.',
            1
        ),
        (
            'T12_C_SEVERE_SIGNS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Eclampsia: seizure, severe headache, visual disturbance, epigastric pain. HELLP: hemolysis, elevated liver enzymes, low platelets.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Sản giật: co giật, đau đầu dữ dội, rối loạn thị giác, đau bụng, buồn nôn/nôn, thiểu niệu. HELLP: tán huyết, tăng men gan, giảm tiểu cầu.',
            1
        ),
        (
            'T12_INF_ECLAMPSIA_CLASSIFICATION',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Classification label: eclampsia.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Nhãn phân loại "Sản giật" (eclampsia) của Bảng 15.',
            1
        ),
        (
            'T12_INF_HELLP_SYNDROME_CLASSIFICATION',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Classification label: HELLP syndrome (Hemolysis, Elevated Liver enzymes, Low Platelets).',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Nhãn phân loại "Hội chứng HELLP" của Bảng 15.',
            1
        ),
        (
            'T12_C_BP_MILD_MODERATE',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Mục 3.6.6. Tăng huyết áp trong thai kỳ',
            'Mild-to-moderate severity: SBP >=140 (but <160) mmHg and/or DBP >=90 (but <110) mmHg, from the paragraph immediately preceding Bảng 15.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'THA nhẹ đến trung bình: đo HA ít nhất 2 lần cách nhau >=4 giờ, HATT >=140 (nhưng <160) mmHg và/hoặc HATTr >=90 (nhưng <110) mmHg.',
            1
        ),
        (
            'T12_C_BP_SEVERE',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Mục 3.6.6. Tăng huyết áp trong thai kỳ',
            'Severe hypertension: SBP >=160 mmHg and/or DBP >=110 mmHg; SBP >=170 mmHg is a medical emergency.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'THA nặng: HATT >=160 mmHg và/hoặc HATTr >=110 mmHg. HATT >=170 mmHg là cấp cứu nội khoa.',
            1
        ),
        (
            'T12_INF_MILD_MODERATE_SEVERITY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Mục 3.6.6. Tăng huyết áp trong thai kỳ',
            'Severity label: mild-to-moderate.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Phân độ "nhẹ đến trung bình".',
            1
        ),
        (
            'T12_INF_SEVERE_SEVERITY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Mục 3.6.6. Tăng huyết áp trong thai kỳ',
            'Severity label: severe.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Phân độ "nặng".',
            1
        ),
        (
            'T12_C_HOME_BP_HIGH',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Home BP >=135/85 mmHg should be treated.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'HA ổn định >=135/85 mmHg đo tại nhà nên được điều trị.',
            1
        ),
        (
            'T12_C_CLINIC_BP_HIGH',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Clinic BP >=140/90 mmHg should be treated.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'HA ổn định >=140/90 mmHg đo tại phòng khám nên được điều trị.',
            1
        ),
        (
            'T12_C_CLINIC_BP_NORMAL',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Complement of the clinic-BP treatment threshold: below threshold.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'HA dưới ngưỡng điều trị đo tại phòng khám.',
            1
        ),
        (
            'T12_INF_METHYLDOPA',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Mild hypertension, first-choice option: methyldopa.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'THA nhẹ, lựa chọn đầu tiên: methyldopa.',
            1
        ),
        (
            'T12_INF_LABETALOL_ORAL',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Mild hypertension, first-choice option: beta-blocker (labetalol).',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'THA nhẹ, lựa chọn đầu tiên: chẹn beta (Labetalol).',
            1
        ),
        (
            'T12_INF_NIFEDIPINE_OR_NICARDIPINE',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Mild hypertension, first-choice option: dihydropyridine CCB (nifedipine [not capsule form], nicardipine).',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'THA nhẹ, lựa chọn đầu tiên: chẹn kênh canxi dihydropyridine (Nifedipine [trừ dạng viên nang], Nicardipine).',
            1
        ),
        (
            'T12_INF_ABSOLUTE_CONTRAINDICATIONS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'RAS-inhibitor drugs (ACEI, ARB, direct renin inhibitors, MRA) are contraindicated in pregnancy.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'THA trong thai kỳ: chống chỉ định dùng các thuốc ức chế RAS (ƯCMC, CTTA, ức chế renin trực tiếp, lợi tiểu kháng thụ thể Mineralocorticoid).',
            1
        ),
        (
            'T12_INF_SEVERE_DRUG_OPTIONS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Severe hypertension: IV labetalol (or IV nicardipine, esmolol, hydralazine, urapidil), oral methyldopa, or dihydropyridine CCB.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'THA nặng: Labetalol TM (hoặc Nicardipine TM, Esmolol, Hydralazine, Urapidil), Methyldopa uống, hoặc CKCa dihydropyridine.',
            1
        ),
        (
            'T12_C_HYPERTENSIVE_CRISIS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'During a hypertensive crisis: add magnesium to prevent eclampsia.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Trong cơn THA: bổ sung magiê để ngăn ngừa sản giật.',
            1
        ),
        (
            'T12_C_PULMONARY_EDEMA',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'In pulmonary edema: IV nitroglycerin infusion; avoid sodium nitroprusside (fetal cyanide toxicity risk).',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Trong phù phổi: truyền TM Nitroglycerin; tránh Natri nitroprusside do nguy cơ nhiễm độc xyanua thai nhi.',
            1
        ),
        (
            'T12_INF_IV_NITROGLYCERIN',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Pulmonary edema management: IV nitroglycerin infusion.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Trong phù phổi: Truyền TM Nitroglycerin.',
            1
        ),
        (
            'T12_INF_MAGNESIUM_SUPPLEMENT',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Hypertensive crisis management: add magnesium sulfate to prevent eclampsia.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Bổ sung magiê trong cơn THA để ngăn ngừa sản giật.',
            1
        ),
        (
            'T12_INF_LABETALOL_MGSO4',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Eclampsia/severe preeclampsia/HELLP: treat immediately (SBP<160, DBP<105 mmHg), labetalol or nicardipine plus magnesium sulfate.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Sản giật/Tiền sản giật nặng/HELLP: ngay lập tức hạ HA, Labetalol hoặc Nicardipine và Magnesium sulfate.',
            1
        ),
        (
            'T12_INF_NICARDIPINE_MGSO4',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Eclampsia/severe preeclampsia/HELLP: treat immediately (SBP<160, DBP<105 mmHg), labetalol or nicardipine plus magnesium sulfate.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Sản giật/Tiền sản giật nặng/HELLP: ngay lập tức hạ HA, Labetalol hoặc Nicardipine và Magnesium sulfate.',
            1
        ),
        (
            'T12_C_IMMEDIATE_TARGET',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 15. Phân loại tăng huyết áp trong thai kỳ (52)',
            'Immediate treatment target: SBP<160 mmHg and DBP<105 mmHg.',
            ARRAY [29]::smallint [],
            ARRAY [31]::smallint [],
            'Đích điều trị ngay lập tức: HATT <160 mmHg và HATTr <105 mmHg.',
            1
        ),
        (
            'T12_C_TARGET_NOT_MET',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Emergency delivery indicated when visual disturbance or coagulopathy is present.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Lấy thai cấp cứu khi có rối loạn thị giác, rối loạn đông cầm máu.',
            1
        ),
        (
            'T12_END_EMERGENCY_DELIVERY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Delivery for gestational hypertension or preeclampsia is recommended at week 37 if asymptomatic; emergency delivery for visual disturbance/coagulopathy.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Chấm dứt thai kỳ trong THA thai kỳ hoặc Tiền sản giật: khuyến cáo ở tuần 37 nếu không triệu chứng; lấy thai cấp cứu khi có rối loạn thị giác/đông cầm máu.',
            1
        ),
        (
            'T12_ACTION_MONITOR_PREGNANCY_POSTPARTUM',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Ongoing management of hypertension in pregnancy: monitor pregnancy status and postpartum course.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Quản lý THA trong thai kỳ theo dõi tình trạng mang thai và hậu sản.',
            1
        ),
        (
            'T12_C_CURRENTLY_PREGNANT',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Branch: still pregnant.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Nhánh còn đang mang thai.',
            1
        ),
        (
            'T12_C_POSTPARTUM',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Branch: postpartum.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Nhánh sau sinh.',
            1
        ),
        (
            'T12_C_HIGH_PREECLAMPSIA_RISK',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Preeclampsia prophylaxis: 75-162 mg aspirin from week 12-36.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Phòng ngừa tiền sản giật: 75-162 mg Aspirin vào tuần 12-36.',
            1
        ),
        (
            'T12_END_ASPIRIN_PROPHYLAXIS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Preeclampsia prophylaxis: 75-162 mg aspirin from week 12-36; oral calcium 1.5-2 g/day recommended for low-calcium diets (<600 mg/day).',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Phòng ngừa tiền sản giật: 75-162 mg Aspirin vào tuần 12-36. Bổ sung canxi 1,5-2 g/ngày được khuyến khích ở phụ nữ có chế độ ăn ít canxi (<600 mg/ngày).',
            1
        ),
        (
            'T12_C_BP_TARGET_ACHIEVED',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Treatment target: clinic DBP 85 mmHg (and SBP 110-140 mmHg).',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Mục tiêu điều trị: HATTr 85 mmHg tại phòng khám (và HATT từ 110-140 mmHg).',
            1
        ),
        (
            'T12_END_MAINTAIN_REGIMEN_PREGNANT',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Target achieved: maintain current regimen.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Đạt mục tiêu điều trị: duy trì phác đồ hiện tại.',
            1
        ),
        (
            'T12_C_BP_TARGET_NOT_ACHIEVED',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Complement of the treatment-target-achieved condition.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Không đạt mục tiêu điều trị.',
            1
        ),
        (
            'T12_END_REFER_OBGYN',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Target not achieved: refer to OB specialist.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Không đạt mục tiêu điều trị: chuyển chuyên khoa Sản.',
            1
        ),
        (
            'T12_C_BREASTFEEDING',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Breastfeeding period: avoid atenolol, propranolol, nifedipine; prefer long-acting CCB.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Thời kỳ cho con bú: tránh Atenolol, Propranolol, Nifedipine; ưu tiên CKCa tác dụng kéo dài.',
            1
        ),
        (
            'T12_C_BP_STILL_HIGH',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Postpartum BP: if still high, any recommended drug may be used except methyldopa (postpartum depression risk).',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'HA sau sinh: nếu HA cao vẫn tiếp diễn, dùng bất kỳ thuốc nào được khuyến cáo trừ Methyldopa (gây trầm cảm sau sinh).',
            1
        ),
        (
            'T12_C_BP_NOT_HIGH',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Postpartum BP no longer high: maintain regimen.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'HA sau sinh không còn cao: duy trì phác đồ.',
            1
        ),
        (
            'T12_ACTION_POSTPARTUM_CONTRAINDICATIONS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Contraindicated: nicardipine. Avoid: atenolol, propranolol, nifedipine. Prefer: methyldopa/long-acting CCB.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Chống chỉ định Nicardipine; tránh Atenolol, Propranolol, Nifedipine; ưu tiên Methyldopa/CKCa tác dụng kéo dài.',
            1
        ),
        (
            'T12_END_MAINTAIN_REGIMEN_POSTPARTUM',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'Postpartum: maintain regimen.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Duy trì phác đồ sau sinh.',
            1
        ),
        (
            'T12_GLOBAL_ABBREVIATION_GLOSSARY',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52), chú thích',
            'Footnote abbreviation glossary for the drug classes named in Bảng 16.',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'Chú giải viết tắt cho các nhóm thuốc nêu trong Bảng 16 (ƯCMC, CTTA, CKCa, LT, MRA, SGLT2i).',
            1
        ),
        (
            'T12_GLOBAL_PREGNANCY_DRUG_CONTRAINDICATIONS',
            'Khuyến cáo của Phân hội Tăng huyết áp - Hội Tim mạch Quốc gia Việt Nam (VSH/VNHA) về Chẩn đoán & Điều trị Tăng huyết áp 2022 (Tóm tắt)',
            '[{"number": "3.6.6", "title": "Tăng huyết áp trong thai kỳ"}]'::jsonb,
            'Bảng 16. Khuyến cáo điều trị tăng huyết áp trong thai kỳ (2, 52)',
            'RAS-inhibitor drugs are contraindicated in pregnancy; avoid sodium nitroprusside (fetal cyanide toxicity risk).',
            ARRAY [30]::smallint [],
            ARRAY [32]::smallint [],
            'THA trong thai kỳ: chống chỉ định thuốc ức chế RAS; tránh Natri nitroprusside do nguy cơ nhiễm độc xyanua thai nhi.',
            1
        )
)
INSERT INTO public.node_source_references (
        "id",
        "node_id",
        "source_title",
        "section_path",
        "locator",
        "locator_detail",
        "printed_page_numbers",
        "pdf_page_numbers",
        "reference_note",
        "reference_order"
    )
SELECT gen_random_uuid(),
    node.id,
    reference_seed.source_title,
    reference_seed.section_path,
    reference_seed.locator,
    reference_seed.locator_detail,
    reference_seed.printed_page_numbers,
    reference_seed.pdf_page_numbers,
    reference_seed.reference_note,
    reference_seed.reference_order
FROM reference_seed
    CROSS JOIN tree_ctx
    JOIN public.decision_nodes node ON node.tree_id = tree_ctx.tree_id
    AND node.node_key = reference_seed.node_key;
COMMIT;
