import { DIAGNOSIS, type PatientPresetDefinition } from './shared'

export const diagnosisPresets: PatientPresetDefinition[] = [
  // ---- Diagnosis Routes ----
  {
    id: 'normal-bp',
    label: 'Healthy Adult â€” Normal BP',
    category: DIAGNOSIS,
    description: 'Textbook normal clinic reading, no risk factors.',
    data: {
      clinic_1_sbp: '120', clinic_1_dbp: '80',
      age: '42', risk_factor_count: '0',
    },
  },
  {
    id: 'stage1-htn',
    label: 'Stage 1 Hypertension â€” Newly Diagnosed',
    category: DIAGNOSIS,
    description: 'Borderline elevated clinic reading; typical new-diagnosis presentation.',
    data: {
      clinic_1_sbp: '135', clinic_1_dbp: '85',
      age: '50', risk_factor_count: '2',
    },
  },
  {
    id: 'stage2-htn',
    label: 'Stage 2 Hypertension',
    category: DIAGNOSIS,
    description: 'Clearly elevated clinic reading.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '55', risk_factor_count: '3',
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'hypertensive-emergency',
    label: 'Hypertensive Emergency',
    category: DIAGNOSIS,
    description: 'SBP â‰¥180 crisis threshold, no acute target organ damage â€” routes to the emergency tree and resolves to urgent (non-crisis) oral therapy.',
    data: {
      clinic_1_sbp: '182', clinic_1_dbp: '80',
      is_pregnant: false,
      has_target_organ_damage: false,
      age: '58', risk_factor_count: '2',
    },
  },
  {
    id: 'hypertensive-emergency-organ-damage',
    label: 'Hypertensive Emergency â€” Acute Target Organ Damage',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute target organ damage but no single identified syndrome â€” falls through to the malignant hypertension/AKI fallback action.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'hypertensive-emergency-acs-to-cad',
    label: 'Hypertensive Emergency â€” Acute Coronary Syndrome',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute coronary syndrome â€” chains from the emergency tree into the coronary-artery-disease tree, which routes to Tree 4 (Essential Treatment Strategy) or Tree 5 (Optimal Treatment Strategy).',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_coronary_syndrome: true,
      has_mi_acs: true,
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      age: '60', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-hypertensive-encephalopathy',
    label: 'Hypertensive Emergency â€” Encephalopathy',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute target organ damage and encephalopathy â€” the first of the eight organ-specific scenario checks, wins ahead of stroke/ACS/etc. Refers to stroke management.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_hypertensive_encephalopathy: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-ais-thrombolysis-candidate',
    label: 'Hypertensive Emergency â€” Acute Ischemic Stroke, Thrombolysis Candidate',
    category: DIAGNOSIS,
    description: 'Crisis BP (>185/110) with acute ischemic stroke and thrombolysis eligibility â€” the second scenario check, targets a tighter 1-hour BP reduction window ahead of thrombolysis.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_ischemic_stroke: true,
      is_thrombolysis_candidate: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-ais-severe',
    label: 'Hypertensive Emergency â€” Acute Ischemic Stroke, Not a Thrombolysis Candidate',
    category: DIAGNOSIS,
    description: 'Very severe crisis BP (>220/120) with acute ischemic stroke but not a thrombolysis candidate â€” falls through to the third scenario check (severe AIS) instead of the thrombolysis-specific one.',
    data: {
      clinic_1_sbp: '230', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_ischemic_stroke: true,
      is_thrombolysis_candidate: false,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-acute-ich',
    label: 'Hypertensive Emergency â€” Acute Intracerebral Hemorrhage',
    category: DIAGNOSIS,
    description: 'Crisis BP (>180 SBP) with acute intracerebral hemorrhage and no ischemic-stroke flags â€” the fourth scenario check.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_intracerebral_hemorrhage: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-pulmonary-edema-heart-failure-chain',
    label: 'Hypertensive Emergency â€” Acute Cardiogenic Pulmonary Edema',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute cardiogenic pulmonary edema (sixth scenario check) â€” chains from the emergency tree into the hypertension-heart-failure tree, which correctly evaluates HFrEF/target-not-reached, but then dies with MissingRuntimePath (context.risk.level) once it links onward into essential-treatment-strategy. That path is normally populated by risk-classification (Tree 2), which the emergency route never visits â€” a genuine, previously undocumented cross-tree contract gap: any emergency patient chained into a modifier tree that continues into essential/optimal-treatment-strategy will error out, not just this one.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_cardiogenic_pulmonary_edema: true,
      current_clinic_sbp: '159', current_clinic_dbp: '97',
      has_hfref: true,
      bp_target_reached: false,
      facility_capability: 'FULL_RESOURCES',
      age: '65', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-acute-aortic-syndrome',
    label: 'Hypertensive Emergency â€” Acute Aortic Syndrome',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute aortic syndrome (seventh scenario check) â€” a strict heart-rate/SBP target ending in its own dedicated END node, distinct from every other emergency sub-syndrome.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_aortic_syndrome: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-eclampsia-pregnancy-chain',
    label: 'Hypertensive Emergency â€” Eclampsia/Severe Preeclampsia/HELLP, Postpartum',
    category: DIAGNOSIS,
    description: 'Crisis BP with the eclampsia/HELLP scenario flag (eighth and last conditional scenario check) â€” chains into the hypertension-in-pregnancy tree via Tree 14â€™s own LINK (distinct from Tree 1â€™s is_pregnant-based entry). Note is_pregnant must be false here: Tree 1 checks is_pregnant before the crisis check and would otherwise divert straight into the pregnancy tree without ever reaching the emergency tree, so this preset can only reach Tree 14â€™s eclampsia scenario with is_pregnant=false â€” a documented tension in how the two trees connect. Once inside, a postpartum + breastfeeding flag routes to the postpartum drug-contraindications branch, testing a part of Tree 12 unreachable via Tree 1â€™s direct pregnancy entry (which always evaluates is_pregnant=true, shadowing the is_postpartum candidate).',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_eclampsia_severe_preeclampsia_or_hellp: true,
      home_sbp: '140', home_dbp: '88',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      has_hypertension_after_week_20: true,
      weeks_resolved_postpartum: '2',
      weeks_persisting_postpartum: '0',
      proteinuria_24h_mg: '50', acr_mg_mmol: '5',
      is_postpartum: true,
      is_breastfeeding: true,
      age: '32', risk_factor_count: '2',
    },
  },

  // ---- Demographic & Comorbidity Diversity ----
]
