import { FOLLOW_UP, MEDICATION_TARGET, type PatientPresetDefinition } from './shared'

export const followUpPresets: PatientPresetDefinition[] = [
  {
    id: 'lifestyle-followup',
    label: 'Lifestyle Follow-Up â€” BP Improved',
    category: FOLLOW_UP,
    description: 'Meets the stored 15/10 mmHg reduction rule after lifestyle changes.',
    data: {
      clinic_1_sbp: '115', clinic_1_dbp: '75',
      is_lifestyle_follow_up: true,
      previous_sbp: '130', previous_dbp: '85',
      previous_target_sbp: '140', previous_target_dbp: '90',
      current_clinic_sbp: '115', current_clinic_dbp: '75',
      age: '55', risk_factor_count: '2',
    },
  },
  {
    id: 'med-followup-reached-full',
    label: 'Medication Follow-Up â€” Target Reached (Full Resources)',
    category: FOLLOW_UP,
    description: 'On initial regimen, current BP within active target, full-resource facility.',
    data: {
      clinic_1_sbp: '129', clinic_1_dbp: '79',
      is_medication_follow_up: true,
      facility_capability: 'FULL_RESOURCES',
      medication_follow_up_stage: 'INITIAL_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '129', current_clinic_dbp: '79',
      age: '60', risk_factor_count: '2',
    },
  },
  {
    id: 'med-followup-reached-limited',
    label: 'Medication Follow-Up â€” Target Reached (Limited Resources)',
    category: FOLLOW_UP,
    description: 'Same as above but a limited-resource facility â€” different terminal action wording.',
    data: {
      clinic_1_sbp: '129', clinic_1_dbp: '79',
      is_medication_follow_up: true,
      facility_capability: 'LIMITED_RESOURCES',
      medication_follow_up_stage: 'INITIAL_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '129', current_clinic_dbp: '79',
      age: '60', risk_factor_count: '2',
    },
  },
  {
    id: 'med-followup-not-reached-initial',
    label: 'Medication Follow-Up â€” Initial Regimen, Target Not Reached',
    category: FOLLOW_UP,
    description: 'Initial regimen insufficient â€” routes toward drug-combination escalation.',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'FULL_RESOURCES',
      medication_follow_up_stage: 'INITIAL_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '130', current_clinic_dbp: '80',
      age: '63', risk_factor_count: '3',
    },
  },
  {
    id: 'med-followup-resistant',
    label: 'Medication Follow-Up â€” Resistant Hypertension (Escalated)',
    category: FOLLOW_UP,
    description: 'Escalated regimen, target not reached â€” resistant hypertension path.',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'FULL_RESOURCES',
      medication_follow_up_stage: 'ESCALATED_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '130', current_clinic_dbp: '80',
      age: '65', risk_factor_count: '3',
    },
  },
  {
    id: 'med-followup-resistant-limited',
    label: 'Medication Follow-Up â€” Resistant Hypertension (Limited Resources)',
    category: FOLLOW_UP,
    description: 'Escalated regimen, target not reached, limited-resource facility â€” reaches resistant-hypertensionâ€™s MRA-tolerated branch and ends in referral since the BP target is still not met.',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'LIMITED_RESOURCES',
      medication_follow_up_stage: 'ESCALATED_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '135', current_clinic_dbp: '85',
      tolerates_mra: true,
      bp_target_reached: false,
      age: '65', risk_factor_count: '3',
    },
  },
  {
    id: 'med-followup-resistant-spironolactone',
    label: 'Medication Follow-Up â€” Resistant HTN, MRA Not Tolerated, Spironolactone Added',
    category: FOLLOW_UP,
    description: 'Escalated regimen, MRA not tolerated but spironolactone is â€” adds spironolactone; BP target reached, so it maintains rather than refers (distinct from the MRA-tolerated preset above).',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'LIMITED_RESOURCES',
      medication_follow_up_stage: 'ESCALATED_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '128', current_clinic_dbp: '78',
      tolerates_mra: false,
      tolerates_spironolactone: true,
      bp_target_reached: true,
      age: '65', risk_factor_count: '3',
    },
  },
  {
    id: 'med-followup-resistant-alternatives',
    label: 'Medication Follow-Up â€” Resistant HTN, Neither MRA Nor Spironolactone Tolerated',
    category: FOLLOW_UP,
    description: 'Escalated regimen, patient tolerates neither MRA nor spironolactone â€” falls through to therapeutic alternatives, still referred since target isnâ€™t met.',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'LIMITED_RESOURCES',
      medication_follow_up_stage: 'ESCALATED_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '135', current_clinic_dbp: '85',
      tolerates_mra: false,
      tolerates_spironolactone: false,
      bp_target_reached: false,
      age: '65', risk_factor_count: '3',
    },
  },

  // ---- Modifier & Complication Trees ----
]
