import { PREGNANCY, type PatientPresetDefinition } from './shared'

export const pregnancyPresets: PatientPresetDefinition[] = [
  {
    id: 'pregnancy-chronic-htn',
    label: 'Pregnancy — Pre-Existing (Chronic) Hypertension',
    category: PREGNANCY,
    description: 'Pregnant with pre-pregnancy hypertension and proteinuria beyond 6 weeks — classified as pre-existing hypertension, a simple terminal diagnosis.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '30', risk_factor_count: '1',
      is_pregnant: true,
      home_sbp: '118', home_dbp: '75',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      has_pre_pregnancy_hypertension: true,
      weeks_persisting_postpartum: '8',
      weeks_resolved_postpartum: '10',
      has_proteinuria: true,
      proteinuria_24h_mg: '100',
      acr_mg_mmol: '5',
    },
  },
  {
    id: 'pregnancy-gestational-mild',
    label: 'Pregnancy — Gestational Hypertension, Mild/Moderate',
    category: PREGNANCY,
    description: 'Hypertension after week 20, not yet resolved postpartum, mild/moderate BP range — classified as gestational hypertension, methyldopa first-line, referred to OB/GYN since the pregnancy BP target isn’t met.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '28', risk_factor_count: '1',
      is_pregnant: true,
      home_sbp: '118', home_dbp: '75',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      has_hypertension_after_week_20: true,
      weeks_resolved_postpartum: '2',
      weeks_persisting_postpartum: '0',
      proteinuria_24h_mg: '50',
      acr_mg_mmol: '5',
    },
  },
  {
    id: 'pregnancy-severe-eclampsia',
    label: 'Pregnancy — Severe Signs (Eclampsia Path)',
    category: PREGNANCY,
    description: 'Severe headache and visual disturbance with no other classification match — routes through the eclampsia/HELLP severe-signs branch to IV labetalol + MgSO4, ending in emergency delivery since the treatment target isn’t met.',
    data: {
      clinic_1_sbp: '155', clinic_1_dbp: '100',
      age: '32', risk_factor_count: '2',
      is_pregnant: true,
      home_sbp: '120', home_dbp: '78',
      current_clinic_sbp: '155', current_clinic_dbp: '100',
      weeks_persisting_postpartum: '0',
      weeks_resolved_postpartum: '0',
      proteinuria_24h_mg: '50',
      acr_mg_mmol: '5',
      has_severe_headache: true,
      has_visual_disturbance: true,
    },
  },
  {
    id: 'pregnancy-high-preeclampsia-risk-aspirin',
    label: 'Pregnancy — High Preeclampsia Risk (Aspirin Prophylaxis)',
    category: PREGNANCY,
    description: 'Gestational hypertension, mild/moderate BP, plus a high-preeclampsia-risk flag — after the drug/contraindication workup, the high-risk check wins over the BP-target checks that follow it, prescribing aspirin prophylaxis instead of referring to OB/GYN.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '28', risk_factor_count: '1',
      is_pregnant: true,
      home_sbp: '118', home_dbp: '75',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      has_hypertension_after_week_20: true,
      weeks_resolved_postpartum: '2',
      weeks_persisting_postpartum: '0',
      proteinuria_24h_mg: '50',
      acr_mg_mmol: '5',
      has_high_preeclampsia_risk: true,
    },
  },
  {
    id: 'pregnancy-bp-target-achieved',
    label: 'Pregnancy — BP Target Achieved (Maintain Regimen)',
    category: PREGNANCY,
    description: 'Gestational hypertension classified via home BP, with current clinic BP threading the narrow 110–140/exactly-85 pregnancy target window — maintains the current regimen instead of referring to OB/GYN, the one outcome not exercised by the other pregnancy presets.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '29', risk_factor_count: '1',
      is_pregnant: true,
      home_sbp: '138', home_dbp: '87',
      current_clinic_sbp: '140', current_clinic_dbp: '85',
      has_hypertension_after_week_20: true,
      weeks_resolved_postpartum: '2',
      weeks_persisting_postpartum: '0',
      proteinuria_24h_mg: '50',
      acr_mg_mmol: '5',
    },
  },
]
