"""create patients, visits, fhir_import_batches tables

Revision ID: 425debaec093
Revises: 8cd7e7adc1fb
Create Date: 2026-07-24 14:41:13.641281

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '425debaec093'
down_revision: str | None = '8cd7e7adc1fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fhir_import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_label', sa.Text(), nullable=False),
    sa.Column('patient_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('visit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fhir_id', sa.Text(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('risk_factor_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('comorbidities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fhir_id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('fhir_encounter_id', sa.Text(), nullable=False),
    sa.Column('visit_number', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('facility_capability', sa.Text(), nullable=True),
    sa.Column('is_early_revisit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('early_revisit_reason', sa.Text(), nullable=True),
    sa.Column('scheduled_next_visit_date', sa.Date(), nullable=True),
    sa.Column('clinic_sbp', sa.Integer(), nullable=True),
    sa.Column('clinic_dbp', sa.Integer(), nullable=True),
    sa.Column('bp_target_sbp', sa.Integer(), nullable=True),
    sa.Column('bp_target_dbp', sa.Integer(), nullable=True),
    sa.Column('bp_controlled', sa.Boolean(), nullable=True),
    sa.Column('hypertension_class', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=True),
    sa.Column('cdss_recommended_action', sa.Text(), nullable=True),
    sa.Column('actual_treatment_action', sa.Text(), nullable=True),
    sa.Column('adherent_to_cdss', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fhir_encounter_id'),
    sa.UniqueConstraint('patient_id', 'visit_number', name='uq_visits_patient_id_visit_number')
    )
    op.create_index('ix_visits_patient_id', 'visits', ['patient_id'], unique=False)
    op.create_index('ix_visits_visit_date', 'visits', ['visit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visits_visit_date', table_name='visits')
    op.drop_index('ix_visits_patient_id', table_name='visits')
    op.drop_table('visits')
    op.drop_table('patients')
    op.drop_table('fhir_import_batches')
    # ### end Alembic commands ###
