"""create initial decision tree schema

Revision ID: 5c43058f54be
Revises: 
Create Date: 2026-06-26 19:47:05.813093

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c43058f54be'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Created/dropped explicitly so the enum type exists before decision_nodes and is
# removed only after it. create_type=False stops the inline column from also
# trying to create it during create_table.
node_type = postgresql.ENUM(
    'START', 'CONDITION', 'INFERENCE', 'ACTION', 'END', 'LINK', 'GLOBAL',
    name='node_type',
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    node_type.create(op.get_bind(), checkfirst=True)
    op.create_table('decision_trees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tree_key', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('name_vi', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_vi'),
    sa.UniqueConstraint('tree_key')
    )
    op.create_table('development_runtime_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inference_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('journey', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("environment IN ('development', 'test')", name='ck_development_runtime_logs_environment'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_development_runtime_logs_created_at', 'development_runtime_logs', ['created_at'], unique=False)
    op.create_index('ix_development_runtime_logs_request_id', 'development_runtime_logs', ['request_id'], unique=False)
    op.create_table('decision_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tree_id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.Text(), nullable=False),
    sa.Column('node_type', node_type, nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_vi', sa.Text(), nullable=False),
    sa.Column('condition_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_patch', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('global_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('link_target_tree_key', sa.Text(), nullable=True),
    sa.Column('link_target_node_key', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['decision_trees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tree_id', 'node_key', name='uq_decision_nodes_tree_id_node_key')
    )
    op.create_table('decision_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_node_id', sa.UUID(), nullable=False),
    sa.Column('to_node_id', sa.UUID(), nullable=False),
    sa.Column('traversal_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['decision_nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['decision_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_node_id', 'to_node_id', name='uq_decision_edges_from_to'),
    sa.UniqueConstraint('from_node_id', 'traversal_order', name='uq_decision_edges_from_traversal_order')
    )
    op.create_index('ix_decision_edges_from_node_id', 'decision_edges', ['from_node_id'], unique=False)
    op.create_index('ix_decision_edges_to_node_id', 'decision_edges', ['to_node_id'], unique=False)
    op.create_table('node_source_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('section_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('locator_detail', sa.Text(), nullable=True),
    sa.Column('printed_page_numbers', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('pdf_page_numbers', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('reference_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['decision_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'reference_order', name='uq_node_source_references_node_id_reference_order')
    )
    op.create_index('ix_node_source_references_node_id', 'node_source_references', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_node_source_references_node_id', table_name='node_source_references')
    op.drop_table('node_source_references')
    op.drop_index('ix_decision_edges_to_node_id', table_name='decision_edges')
    op.drop_index('ix_decision_edges_from_node_id', table_name='decision_edges')
    op.drop_table('decision_edges')
    op.drop_table('decision_nodes')
    op.drop_index('ix_development_runtime_logs_request_id', table_name='development_runtime_logs')
    op.drop_index('ix_development_runtime_logs_created_at', table_name='development_runtime_logs')
    op.drop_table('development_runtime_logs')
    op.drop_table('decision_trees')
    node_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
