"""restructure clinical schema for icd10/snomed/loinc/atc code alignment

Revision ID: 68b4b4838af0
Revises: 425debaec093
Create Date: 2026-07-24 15:51:51.413259

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68b4b4838af0'
down_revision: str | None = '425debaec093'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('fhir_condition_id', sa.Text(), nullable=False),
    sa.Column('icd10_code', sa.Text(), nullable=True),
    sa.Column('snomed_code', sa.Text(), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'fhir_condition_id', name='uq_patient_conditions_patient_id_fhir_id')
    )
    op.create_index('ix_patient_conditions_icd10_code', 'patient_conditions', ['icd10_code'], unique=False)
    op.create_index('ix_patient_conditions_patient_id', 'patient_conditions', ['patient_id'], unique=False)
    op.create_table('visit_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.Text(), nullable=True),
    sa.Column('drug_name', sa.Text(), nullable=False),
    sa.Column('drug_class_note', sa.Text(), nullable=True),
    sa.Column('dose_value', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['medicines.drug_id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_medications_drug_id', 'visit_medications', ['drug_id'], unique=False)
    op.create_index('ix_visit_medications_visit_id', 'visit_medications', ['visit_id'], unique=False)
    op.create_table('visit_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('loinc_code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_observations_loinc_code', 'visit_observations', ['loinc_code'], unique=False)
    op.create_index('ix_visit_observations_visit_id', 'visit_observations', ['visit_id'], unique=False)
    op.add_column('medicines', sa.Column('atc_code', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('department', sa.Text(), nullable=True))
    op.drop_column('patients', 'comorbidities')
    op.drop_column('visits', 'actual_treatment_action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('actual_treatment_action', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('comorbidities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('patients', 'department')
    op.drop_column('medicines', 'atc_code')
    op.drop_index('ix_visit_observations_visit_id', table_name='visit_observations')
    op.drop_index('ix_visit_observations_loinc_code', table_name='visit_observations')
    op.drop_table('visit_observations')
    op.drop_index('ix_visit_medications_visit_id', table_name='visit_medications')
    op.drop_index('ix_visit_medications_drug_id', table_name='visit_medications')
    op.drop_table('visit_medications')
    op.drop_index('ix_patient_conditions_patient_id', table_name='patient_conditions')
    op.drop_index('ix_patient_conditions_icd10_code', table_name='patient_conditions')
    op.drop_table('patient_conditions')
    # ### end Alembic commands ###
