import type { PatientFormData } from './MockPatientSidebar'

export interface PatientPreset {
  id: string
  label: string
  category: string
  description: string
  data: Partial<PatientFormData>
}

const DIAGNOSIS = 'Diagnosis Routes'
const DEMOGRAPHIC = 'Demographic & Comorbidity Diversity'
const FOLLOW_UP = 'Follow-Up Visits'
const MODIFIER_TREES = 'Modifier & Complication Trees'
const PREGNANCY = 'Pregnancy & Postpartum'

const MEDICATION_TARGET: Pick<
  PatientFormData,
  'has_active_bp_target' | 'target_sbp_upper' | 'target_dbp_upper'
> = {
  has_active_bp_target: true,
  target_sbp_upper: '130',
  target_dbp_upper: '80',
}

export const PATIENT_PRESETS: PatientPreset[] = [
  // ---- Diagnosis Routes ----
  {
    id: 'normal-bp',
    label: 'Healthy Adult — Normal BP',
    category: DIAGNOSIS,
    description: 'Textbook normal readings, no risk factors.',
    data: {
      clinic_1_sbp: '120', clinic_1_dbp: '80',
      clinic_2_sbp: '120', clinic_2_dbp: '80',
      clinic_3_sbp: '120', clinic_3_dbp: '80',
      age: '42', risk_factor_count: '0',
    },
  },
  {
    id: 'stage1-htn',
    label: 'Stage 1 Hypertension — Newly Diagnosed',
    category: DIAGNOSIS,
    description: 'Borderline elevated clinic readings; typical new-diagnosis presentation.',
    data: {
      clinic_1_sbp: '135', clinic_1_dbp: '85',
      clinic_2_sbp: '138', clinic_2_dbp: '86',
      clinic_3_sbp: '136', clinic_3_dbp: '84',
      age: '50', risk_factor_count: '2',
    },
  },
  {
    id: 'stage2-htn',
    label: 'Stage 2 Hypertension',
    category: DIAGNOSIS,
    description: 'Clearly elevated clinic readings across all three visits.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      clinic_2_sbp: '148', clinic_2_dbp: '93',
      clinic_3_sbp: '152', clinic_3_dbp: '96',
      age: '55', risk_factor_count: '3',
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'hypertensive-emergency',
    label: 'Hypertensive Emergency',
    category: DIAGNOSIS,
    description: 'SBP ≥180 crisis threshold, no acute target organ damage — routes to the emergency tree and resolves to urgent (non-crisis) oral therapy.',
    data: {
      clinic_1_sbp: '182', clinic_1_dbp: '80',
      is_pregnant: false,
      has_target_organ_damage: false,
      age: '58', risk_factor_count: '2',
    },
  },
  {
    id: 'hypertensive-emergency-organ-damage',
    label: 'Hypertensive Emergency — Acute Target Organ Damage',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute target organ damage but no single identified syndrome — falls through to the malignant hypertension/AKI fallback action.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'hypertensive-emergency-acs-to-cad',
    label: 'Hypertensive Emergency — Acute Coronary Syndrome',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute coronary syndrome — chains from the emergency tree into the (now-seeded) coronary-artery-disease tree, which itself ends on a documented dead LINK (T9_LINK_4_5 targets a nonexistent tree_key, a pre-existing seed-data bug).',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_coronary_syndrome: true,
      has_mi_acs: true,
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      age: '60', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-hypertensive-encephalopathy',
    label: 'Hypertensive Emergency — Encephalopathy',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute target organ damage and encephalopathy — the first of the eight organ-specific scenario checks, wins ahead of stroke/ACS/etc. Refers to stroke management.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_hypertensive_encephalopathy: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-ais-thrombolysis-candidate',
    label: 'Hypertensive Emergency — Acute Ischemic Stroke, Thrombolysis Candidate',
    category: DIAGNOSIS,
    description: 'Crisis BP (>185/110) with acute ischemic stroke and thrombolysis eligibility — the second scenario check, targets a tighter 1-hour BP reduction window ahead of thrombolysis.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_ischemic_stroke: true,
      is_thrombolysis_candidate: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-ais-severe',
    label: 'Hypertensive Emergency — Acute Ischemic Stroke, Not a Thrombolysis Candidate',
    category: DIAGNOSIS,
    description: 'Very severe crisis BP (>220/120) with acute ischemic stroke but not a thrombolysis candidate — falls through to the third scenario check (severe AIS) instead of the thrombolysis-specific one.',
    data: {
      clinic_1_sbp: '230', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_ischemic_stroke: true,
      is_thrombolysis_candidate: false,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-acute-ich',
    label: 'Hypertensive Emergency — Acute Intracerebral Hemorrhage',
    category: DIAGNOSIS,
    description: 'Crisis BP (>180 SBP) with acute intracerebral hemorrhage and no ischemic-stroke flags — the fourth scenario check.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_intracerebral_hemorrhage: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-pulmonary-edema-heart-failure-chain',
    label: 'Hypertensive Emergency — Acute Cardiogenic Pulmonary Edema',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute cardiogenic pulmonary edema (sixth scenario check) — chains from the emergency tree into the hypertension-heart-failure tree, which correctly evaluates HFrEF/target-not-reached, but then dies with MissingRuntimePath (context.risk.level) once it links onward into essential-treatment-strategy. That path is normally populated by risk-classification (Tree 2), which the emergency route never visits — a genuine, previously undocumented cross-tree contract gap: any emergency patient chained into a modifier tree that continues into essential/optimal-treatment-strategy will error out, not just this one.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_cardiogenic_pulmonary_edema: true,
      current_clinic_sbp: '159', current_clinic_dbp: '97',
      has_hfref: true,
      bp_target_reached: false,
      facility_capability: 'FULL_RESOURCES',
      age: '65', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-acute-aortic-syndrome',
    label: 'Hypertensive Emergency — Acute Aortic Syndrome',
    category: DIAGNOSIS,
    description: 'Crisis BP with acute aortic syndrome (seventh scenario check) — a strict heart-rate/SBP target ending in its own dedicated END node, distinct from every other emergency sub-syndrome.',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_acute_aortic_syndrome: true,
      age: '58', risk_factor_count: '3',
    },
  },
  {
    id: 'emergency-eclampsia-pregnancy-chain',
    label: 'Hypertensive Emergency — Eclampsia/Severe Preeclampsia/HELLP, Postpartum',
    category: DIAGNOSIS,
    description: 'Crisis BP with the eclampsia/HELLP scenario flag (eighth and last conditional scenario check) — chains into the hypertension-in-pregnancy tree via Tree 14’s own LINK (distinct from Tree 1’s is_pregnant-based entry). Note is_pregnant must be false here: Tree 1 checks is_pregnant before the crisis check and would otherwise divert straight into the pregnancy tree without ever reaching the emergency tree, so this preset can only reach Tree 14’s eclampsia scenario with is_pregnant=false — a documented tension in how the two trees connect. Once inside, a postpartum + breastfeeding flag routes to the postpartum drug-contraindications branch, testing a part of Tree 12 unreachable via Tree 1’s direct pregnancy entry (which always evaluates is_pregnant=true, shadowing the is_postpartum candidate).',
    data: {
      clinic_1_sbp: '200', clinic_1_dbp: '124',
      is_pregnant: false,
      has_target_organ_damage: true,
      has_eclampsia_severe_preeclampsia_or_hellp: true,
      home_sbp: '140', home_dbp: '88',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      has_hypertension_after_week_20: true,
      weeks_resolved_postpartum: '2',
      weeks_persisting_postpartum: '0',
      proteinuria_24h_mg: '50', acr_mg_mmol: '5',
      is_postpartum: true,
      is_breastfeeding: true,
      age: '32', risk_factor_count: '2',
    },
  },
  {
    id: 'ambulatory-confirmation',
    label: 'Borderline BP — Home/Ambulatory Confirmation',
    category: DIAGNOSIS,
    description: 'Ambiguous clinic readings plus a full set of out-of-office measurements.',
    data: {
      clinic_1_sbp: '138', clinic_1_dbp: '86',
      clinic_2_sbp: '136', clinic_2_dbp: '85',
      clinic_3_sbp: '139', clinic_3_dbp: '87',
      home_sbp: '135', home_dbp: '85',
      daytime_sbp: '138', daytime_dbp: '87',
      morning_sbp: '140', morning_dbp: '88',
      bp_24h_sbp: '132', bp_24h_dbp: '84',
      age: '50', risk_factor_count: '2',
    },
  },

  // ---- Demographic & Comorbidity Diversity ----
  {
    id: 'elderly-ckd',
    label: 'Elderly with CKD Stage 3+ & Organ Damage',
    category: DEMOGRAPHIC,
    description: '78-year-old with chronic kidney disease and target organ damage.',
    data: {
      clinic_1_sbp: '155', clinic_1_dbp: '92',
      clinic_2_sbp: '152', clinic_2_dbp: '90',
      clinic_3_sbp: '156', clinic_3_dbp: '93',
      age: '78', risk_factor_count: '4',
      has_ckd: true, has_ckd_stage_3_or_higher: true, has_target_organ_damage: true,
    },
  },
  {
    id: 'diabetic-cad',
    label: 'Diabetic with Coronary Artery Disease',
    category: DEMOGRAPHIC,
    description: '62-year-old with type 2 diabetes and established CAD. CAD is checked before type-2-diabetes in Tree 3’s modifier order, so this routes into the coronary-artery-disease tree (CCS angina action); the diabetes flag is recorded but that tree never runs in this same traversal. Ends on a documented dead LINK (T9_LINK_4_5 targets a nonexistent tree_key, a pre-existing seed-data bug — same one hit by the emergency→ACS preset).',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '94',
      clinic_2_sbp: '146', clinic_2_dbp: '92',
      clinic_3_sbp: '150', clinic_3_dbp: '95',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      age: '62', risk_factor_count: '5',
      has_type_2_diabetes: true, has_diabetes: true,
      has_coronary_artery_disease: true, has_cardiovascular_disease: true,
      has_ccs_angina: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'post-stroke',
    label: 'Post-Stroke / TIA History',
    category: DEMOGRAPHIC,
    description: '70-year-old with prior stroke and TIA.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '92',
      clinic_2_sbp: '148', clinic_2_dbp: '90',
      clinic_3_sbp: '151', clinic_3_dbp: '93',
      age: '70', risk_factor_count: '4',
      has_stroke: true, has_tia: true, has_cardiovascular_disease: true,
    },
  },
  {
    id: 'frail-elderly',
    label: 'Frail Older Adult with Heart Failure',
    category: DEMOGRAPHIC,
    description: '85-year-old, frailty syndrome and heart failure. Heart failure is checked before the (unseeded) older-adult modifier at Tree 3, so this now routes into the heart-failure tree — HFrEF, target not yet reached — instead of the older-adult dead link.',
    data: {
      clinic_1_sbp: '158', clinic_1_dbp: '96',
      clinic_2_sbp: '156', clinic_2_dbp: '94',
      clinic_3_sbp: '159', clinic_3_dbp: '97',
      current_clinic_sbp: '159', current_clinic_dbp: '97',
      age: '85', risk_factor_count: '2',
      has_frailty_syndrome: true, has_heart_failure: true,
      has_hfref: true,
      bp_target_reached: false,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'high-risk-young',
    label: 'Young Adult, High Risk-Factor Load',
    category: DEMOGRAPHIC,
    description: '45-year-old, no diagnosed comorbidities yet but 8 risk factors.',
    data: {
      clinic_1_sbp: '138', clinic_1_dbp: '88',
      clinic_2_sbp: '140', clinic_2_dbp: '89',
      clinic_3_sbp: '137', clinic_3_dbp: '87',
      age: '45', risk_factor_count: '8',
      facility_capability: 'FULL_RESOURCES',
    },
  },

  // ---- Follow-Up Visits ----
  {
    id: 'lifestyle-followup',
    label: 'Lifestyle Follow-Up — BP Improved',
    category: FOLLOW_UP,
    description: 'Meets the stored 10/5 mmHg reduction rule after lifestyle changes.',
    data: {
      clinic_1_sbp: '140', clinic_1_dbp: '90',
      is_lifestyle_follow_up: true,
      pre_lifestyle_clinic_sbp: '150', pre_lifestyle_clinic_dbp: '95',
      current_clinic_sbp: '140', current_clinic_dbp: '90',
      age: '55', risk_factor_count: '2',
    },
  },
  {
    id: 'med-followup-reached-full',
    label: 'Medication Follow-Up — Target Reached (Full Resources)',
    category: FOLLOW_UP,
    description: 'On initial regimen, current BP within active target, full-resource facility.',
    data: {
      clinic_1_sbp: '129', clinic_1_dbp: '79',
      is_medication_follow_up: true,
      facility_capability: 'FULL_RESOURCES',
      medication_follow_up_stage: 'INITIAL_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '129', current_clinic_dbp: '79',
      age: '60', risk_factor_count: '2',
    },
  },
  {
    id: 'med-followup-reached-limited',
    label: 'Medication Follow-Up — Target Reached (Limited Resources)',
    category: FOLLOW_UP,
    description: 'Same as above but a limited-resource facility — different terminal action wording.',
    data: {
      clinic_1_sbp: '129', clinic_1_dbp: '79',
      is_medication_follow_up: true,
      facility_capability: 'LIMITED_RESOURCES',
      medication_follow_up_stage: 'INITIAL_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '129', current_clinic_dbp: '79',
      age: '60', risk_factor_count: '2',
    },
  },
  {
    id: 'med-followup-not-reached-initial',
    label: 'Medication Follow-Up — Initial Regimen, Target Not Reached',
    category: FOLLOW_UP,
    description: 'Initial regimen insufficient — routes toward drug-combination escalation.',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'FULL_RESOURCES',
      medication_follow_up_stage: 'INITIAL_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '130', current_clinic_dbp: '80',
      age: '63', risk_factor_count: '3',
    },
  },
  {
    id: 'med-followup-resistant',
    label: 'Medication Follow-Up — Resistant Hypertension (Escalated)',
    category: FOLLOW_UP,
    description: 'Escalated regimen, target not reached — resistant hypertension path.',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'FULL_RESOURCES',
      medication_follow_up_stage: 'ESCALATED_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '130', current_clinic_dbp: '80',
      age: '65', risk_factor_count: '3',
    },
  },
  {
    id: 'med-followup-resistant-limited',
    label: 'Medication Follow-Up — Resistant Hypertension (Limited Resources)',
    category: FOLLOW_UP,
    description: 'Escalated regimen, target not reached, limited-resource facility — reaches resistant-hypertension’s MRA-tolerated branch and ends in referral since the BP target is still not met.',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'LIMITED_RESOURCES',
      medication_follow_up_stage: 'ESCALATED_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '135', current_clinic_dbp: '85',
      tolerates_mra: true,
      bp_target_reached: false,
      age: '65', risk_factor_count: '3',
    },
  },
  {
    id: 'med-followup-resistant-spironolactone',
    label: 'Medication Follow-Up — Resistant HTN, MRA Not Tolerated, Spironolactone Added',
    category: FOLLOW_UP,
    description: 'Escalated regimen, MRA not tolerated but spironolactone is — adds spironolactone; BP target reached, so it maintains rather than refers (distinct from the MRA-tolerated preset above).',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'LIMITED_RESOURCES',
      medication_follow_up_stage: 'ESCALATED_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '128', current_clinic_dbp: '78',
      tolerates_mra: false,
      tolerates_spironolactone: true,
      bp_target_reached: true,
      age: '65', risk_factor_count: '3',
    },
  },
  {
    id: 'med-followup-resistant-alternatives',
    label: 'Medication Follow-Up — Resistant HTN, Neither MRA Nor Spironolactone Tolerated',
    category: FOLLOW_UP,
    description: 'Escalated regimen, patient tolerates neither MRA nor spironolactone — falls through to therapeutic alternatives, still referred since target isn’t met.',
    data: {
      clinic_1_sbp: '130', clinic_1_dbp: '80',
      is_medication_follow_up: true,
      facility_capability: 'LIMITED_RESOURCES',
      medication_follow_up_stage: 'ESCALATED_REGIMEN',
      ...MEDICATION_TARGET,
      current_clinic_sbp: '135', current_clinic_dbp: '85',
      tolerates_mra: false,
      tolerates_spironolactone: false,
      bp_target_reached: false,
      age: '65', risk_factor_count: '3',
    },
  },

  // ---- Modifier & Complication Trees ----
  {
    id: 'ckd-modifier',
    label: 'Chronic Kidney Disease Modifier',
    category: MODIFIER_TREES,
    description: '50-year-old, CKD only (no heart failure/CAD, which take precedence at Tree 3) — reaches the chronic-kidney-disease tree’s default path (no prior creatinine test on file, so it tests and monitors), then continues into the mainline optimal-treatment-strategy/drug-combination trees.',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '92',
      clinic_2_sbp: '146', clinic_2_dbp: '90',
      clinic_3_sbp: '150', clinic_3_dbp: '93',
      current_clinic_sbp: '135', current_clinic_dbp: '92',
      age: '50', risk_factor_count: '2',
      has_ckd: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'type2-diabetes-modifier',
    label: 'Type 2 Diabetes Modifier — Above Target with CV Risk',
    category: MODIFIER_TREES,
    description: '50-year-old, type-2 diabetes with cardiovascular disease and BP above target — reaches the type-2-diabetes tree’s CV-risk branch (adds SGLT2 inhibitor / GLP-1 RA), then continues into the mainline optimal-treatment-strategy/drug-combination trees.',
    data: {
      clinic_1_sbp: '145', clinic_1_dbp: '90',
      clinic_2_sbp: '143', clinic_2_dbp: '88',
      clinic_3_sbp: '146', clinic_3_dbp: '91',
      current_clinic_sbp: '135', current_clinic_dbp: '88',
      age: '50', risk_factor_count: '3',
      has_type_2_diabetes: true,
      has_cardiovascular_disease: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'type2-diabetes-no-cv-risk-maintain',
    label: 'Type 2 Diabetes Modifier — No CV Risk, Maintain Regimen',
    category: MODIFIER_TREES,
    description: '50-year-old, type-2 diabetes with no cardiovascular disease/stroke/CAD and BP above target — takes the no-CV-risk branch (maintain current regimen, no SGLT2i/GLP-1 RA added), contrasting with the CV-risk preset above.',
    data: {
      clinic_1_sbp: '145', clinic_1_dbp: '90',
      clinic_2_sbp: '143', clinic_2_dbp: '88',
      clinic_3_sbp: '146', clinic_3_dbp: '91',
      current_clinic_sbp: '135', current_clinic_dbp: '88',
      age: '50', risk_factor_count: '1',
      has_type_2_diabetes: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'cad-revascularization',
    label: 'Coronary Artery Disease — Post-Revascularization (No Beta-Blocker)',
    category: MODIFIER_TREES,
    description: '55-year-old with CAD and a history of CCS revascularization (no AMI/CCS angina) — takes the "no routine beta-blocker" branch. Ends on the same documented dead LINK as the other CAD presets (T9_LINK_4_5 targets a nonexistent tree_key).',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '94',
      clinic_2_sbp: '146', clinic_2_dbp: '92',
      clinic_3_sbp: '150', clinic_3_dbp: '95',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      age: '55', risk_factor_count: '3',
      has_coronary_artery_disease: true, has_cardiovascular_disease: true,
      has_ccs_revasc: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'cad-cabg-history',
    label: 'Coronary Artery Disease — Prior CABG (Early Beta-Blocker)',
    category: MODIFIER_TREES,
    description: '55-year-old with CAD and a history of CABG (no AMI/angina/revasc flags) — takes the "early beta-blocker" branch, the last of the four CAD drug-recommendation branches. Same documented dead-LINK ending.',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '94',
      clinic_2_sbp: '146', clinic_2_dbp: '92',
      clinic_3_sbp: '150', clinic_3_dbp: '95',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      age: '55', risk_factor_count: '3',
      has_coronary_artery_disease: true, has_cardiovascular_disease: true,
      has_cabg: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'comorbidity-modifier-below-threshold-gap',
    label: 'Comorbidity Modifier — Unreachable When BP Already Below Threshold',
    category: MODIFIER_TREES,
    description: '55-year-old with CAD whose current BP is already below Tree 3’s own "at or above threshold" gate (which requires sbp≥130 or dbp≥90 before it will even present the comorbidity flag to a modifier tree). Result: the patient never reaches the coronary-artery-disease tree at all and instead exits via Tree 3’s generic lifestyle/follow-up action — meaning the "already at target" bypass branches inside the CAD, heart-failure, and type-2-diabetes trees (T9_C_BP3/BP4, T10_C_BP1, T8_C_BELOW_TARGET) are all structurally unreachable via normal routing, not exercisable by any preset.',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '94',
      clinic_2_sbp: '146', clinic_2_dbp: '92',
      clinic_3_sbp: '150', clinic_3_dbp: '95',
      current_clinic_sbp: '125', current_clinic_dbp: '80',
      age: '55', risk_factor_count: '3',
      has_coronary_artery_disease: true, has_cardiovascular_disease: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'heart-failure-hfmref',
    label: 'Heart Failure — Mildly Reduced EF (HFmrEF)',
    category: MODIFIER_TREES,
    description: '65-year-old with HFmrEF, BP target not yet reached — adds SGLT2i/aldosterone antagonist then ARNI/CTTA, distinct from the HFrEF branch tested elsewhere.',
    data: {
      clinic_1_sbp: '158', clinic_1_dbp: '96',
      clinic_2_sbp: '156', clinic_2_dbp: '94',
      clinic_3_sbp: '159', clinic_3_dbp: '97',
      current_clinic_sbp: '159', current_clinic_dbp: '97',
      age: '65', risk_factor_count: '2',
      has_heart_failure: true,
      has_hfmref: true,
      bp_target_reached: false,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'heart-failure-hfpef',
    label: 'Heart Failure — Preserved EF (HFpEF)',
    category: MODIFIER_TREES,
    description: '65-year-old with HFpEF, BP target not yet reached — combines diuretic/SGLT2i/aldosterone antagonist then ARNI/CTTA, the third of the four EF-category branches.',
    data: {
      clinic_1_sbp: '158', clinic_1_dbp: '96',
      clinic_2_sbp: '156', clinic_2_dbp: '94',
      clinic_3_sbp: '159', clinic_3_dbp: '97',
      current_clinic_sbp: '159', current_clinic_dbp: '97',
      age: '65', risk_factor_count: '2',
      has_heart_failure: true,
      has_hfpef: true,
      bp_target_reached: false,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'heart-failure-lvh',
    label: 'Heart Failure Tree — LVH (No Reduced EF)',
    category: MODIFIER_TREES,
    description: '65-year-old with left ventricular hypertrophy but no HFrEF/HFmrEF/HFpEF flag, BP target not yet reached — the fourth and last EF-evaluation branch, adds an A+C or A+D combination.',
    data: {
      clinic_1_sbp: '158', clinic_1_dbp: '96',
      clinic_2_sbp: '156', clinic_2_dbp: '94',
      clinic_3_sbp: '159', clinic_3_dbp: '97',
      current_clinic_sbp: '159', current_clinic_dbp: '97',
      age: '65', risk_factor_count: '2',
      has_heart_failure: true,
      has_lvh: true,
      bp_target_reached: false,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'heart-failure-target-reached',
    label: 'Heart Failure — HFrEF, BP Target Reached (Maintain)',
    category: MODIFIER_TREES,
    description: '65-year-old with HFrEF whose BP is above the entry threshold but already at the personal target — after EF evaluation, maintains the current regimen instead of adding a CCB/adjusting dosage.',
    data: {
      clinic_1_sbp: '158', clinic_1_dbp: '96',
      clinic_2_sbp: '156', clinic_2_dbp: '94',
      clinic_3_sbp: '159', clinic_3_dbp: '97',
      current_clinic_sbp: '132', current_clinic_dbp: '86',
      age: '65', risk_factor_count: '2',
      has_heart_failure: true,
      has_hfref: true,
      bp_target_reached: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'ckd-kidney-transplant',
    label: 'Chronic Kidney Disease — Post-Transplant',
    category: MODIFIER_TREES,
    description: '50-year-old with CKD and a kidney transplant — uses the stricter post-transplant BP target (130/80) and a narrower combination list, then maintains the current regimen.',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '92',
      clinic_2_sbp: '146', clinic_2_dbp: '90',
      clinic_3_sbp: '150', clinic_3_dbp: '93',
      current_clinic_sbp: '135', current_clinic_dbp: '92',
      age: '50', risk_factor_count: '2',
      has_ckd: true,
      has_kidney_transplant: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'ckd-ras-inhibitor-stopped',
    label: 'Chronic Kidney Disease — Prior Test, RAS Inhibitor Already Stopped',
    category: MODIFIER_TREES,
    description: '50-year-old with CKD, has a prior creatinine test on file, and is no longer on a RAS inhibitor — maintains the current regimen without re-testing creatinine.',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '92',
      clinic_2_sbp: '146', clinic_2_dbp: '90',
      clinic_3_sbp: '150', clinic_3_dbp: '93',
      current_clinic_sbp: '135', current_clinic_dbp: '92',
      age: '50', risk_factor_count: '2',
      has_ckd: true,
      has_prior_creatinine_test: true,
      still_using_ras_inhibitor: false,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'ckd-creatinine-increased',
    label: 'Chronic Kidney Disease — Creatinine Rose >30% on RAS Inhibitor',
    category: MODIFIER_TREES,
    description: '50-year-old with CKD, still on a RAS inhibitor, prior creatinine test shows a >30% rise — reduces the dose or stops the RAS inhibitor and flags for clinician review.',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '92',
      clinic_2_sbp: '146', clinic_2_dbp: '90',
      clinic_3_sbp: '150', clinic_3_dbp: '93',
      current_clinic_sbp: '135', current_clinic_dbp: '92',
      age: '50', risk_factor_count: '2',
      has_ckd: true,
      has_prior_creatinine_test: true,
      still_using_ras_inhibitor: true,
      creatinine_increased_over_30_percent: true,
      facility_capability: 'FULL_RESOURCES',
    },
  },
  {
    id: 'ckd-creatinine-stable',
    label: 'Chronic Kidney Disease — Creatinine Stable on RAS Inhibitor',
    category: MODIFIER_TREES,
    description: '50-year-old with CKD, still on a RAS inhibitor, prior creatinine test shows no significant rise — maintains the current regimen since creatinine is stable.',
    data: {
      clinic_1_sbp: '148', clinic_1_dbp: '92',
      clinic_2_sbp: '146', clinic_2_dbp: '90',
      clinic_3_sbp: '150', clinic_3_dbp: '93',
      current_clinic_sbp: '135', current_clinic_dbp: '92',
      age: '50', risk_factor_count: '2',
      has_ckd: true,
      has_prior_creatinine_test: true,
      still_using_ras_inhibitor: true,
      creatinine_increased_over_30_percent: false,
      facility_capability: 'FULL_RESOURCES',
    },
  },

  // ---- Pregnancy & Postpartum ----
  {
    id: 'pregnancy-chronic-htn',
    label: 'Pregnancy — Pre-Existing (Chronic) Hypertension',
    category: PREGNANCY,
    description: 'Pregnant with pre-pregnancy hypertension and proteinuria beyond 6 weeks — classified as pre-existing hypertension, a simple terminal diagnosis.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '30', risk_factor_count: '1',
      is_pregnant: true,
      home_sbp: '118', home_dbp: '75',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      has_pre_pregnancy_hypertension: true,
      weeks_persisting_postpartum: '8',
      weeks_resolved_postpartum: '10',
      has_proteinuria: true,
      proteinuria_24h_mg: '100',
      acr_mg_mmol: '5',
    },
  },
  {
    id: 'pregnancy-gestational-mild',
    label: 'Pregnancy — Gestational Hypertension, Mild/Moderate',
    category: PREGNANCY,
    description: 'Hypertension after week 20, not yet resolved postpartum, mild/moderate BP range — classified as gestational hypertension, methyldopa first-line, referred to OB/GYN since the pregnancy BP target isn’t met.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '28', risk_factor_count: '1',
      is_pregnant: true,
      home_sbp: '118', home_dbp: '75',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      has_hypertension_after_week_20: true,
      weeks_resolved_postpartum: '2',
      weeks_persisting_postpartum: '0',
      proteinuria_24h_mg: '50',
      acr_mg_mmol: '5',
    },
  },
  {
    id: 'pregnancy-severe-eclampsia',
    label: 'Pregnancy — Severe Signs (Eclampsia Path)',
    category: PREGNANCY,
    description: 'Severe headache and visual disturbance with no other classification match — routes through the eclampsia/HELLP severe-signs branch to IV labetalol + MgSO4, ending in emergency delivery since the treatment target isn’t met.',
    data: {
      clinic_1_sbp: '155', clinic_1_dbp: '100',
      age: '32', risk_factor_count: '2',
      is_pregnant: true,
      home_sbp: '120', home_dbp: '78',
      current_clinic_sbp: '155', current_clinic_dbp: '100',
      weeks_persisting_postpartum: '0',
      weeks_resolved_postpartum: '0',
      proteinuria_24h_mg: '50',
      acr_mg_mmol: '5',
      has_severe_headache: true,
      has_visual_disturbance: true,
    },
  },
  {
    id: 'pregnancy-high-preeclampsia-risk-aspirin',
    label: 'Pregnancy — High Preeclampsia Risk (Aspirin Prophylaxis)',
    category: PREGNANCY,
    description: 'Gestational hypertension, mild/moderate BP, plus a high-preeclampsia-risk flag — after the drug/contraindication workup, the high-risk check wins over the BP-target checks that follow it, prescribing aspirin prophylaxis instead of referring to OB/GYN.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '28', risk_factor_count: '1',
      is_pregnant: true,
      home_sbp: '118', home_dbp: '75',
      current_clinic_sbp: '150', current_clinic_dbp: '95',
      has_hypertension_after_week_20: true,
      weeks_resolved_postpartum: '2',
      weeks_persisting_postpartum: '0',
      proteinuria_24h_mg: '50',
      acr_mg_mmol: '5',
      has_high_preeclampsia_risk: true,
    },
  },
  {
    id: 'pregnancy-bp-target-achieved',
    label: 'Pregnancy — BP Target Achieved (Maintain Regimen)',
    category: PREGNANCY,
    description: 'Gestational hypertension classified via home BP, with current clinic BP threading the narrow 110–140/exactly-85 pregnancy target window — maintains the current regimen instead of referring to OB/GYN, the one outcome not exercised by the other pregnancy presets.',
    data: {
      clinic_1_sbp: '150', clinic_1_dbp: '95',
      age: '29', risk_factor_count: '1',
      is_pregnant: true,
      home_sbp: '138', home_dbp: '87',
      current_clinic_sbp: '140', current_clinic_dbp: '85',
      has_hypertension_after_week_20: true,
      weeks_resolved_postpartum: '2',
      weeks_persisting_postpartum: '0',
      proteinuria_24h_mg: '50',
      acr_mg_mmol: '5',
    },
  },
]
