"""Public domain contracts for the generic decision-tree engine."""

from cdss.domain.decision_tree.actions import collect_action
from cdss.domain.decision_tree.conditions import (
    ConditionEvaluation,
    evaluate_candidate_condition,
    evaluate_condition,
    validate_condition_definition,
)
from cdss.domain.decision_tree.contracts import (
    ExecutedAction,
    ExecutedReference,
    FrozenJsonObject,
    JsonObject,
    JsonValue,
    NodeType,
    RunState,
    TraceEvent,
    TraversalResult,
    TraversalTraceEntry,
    TreeMetadata,
)
from cdss.domain.decision_tree.errors import (
    ContextPatchError,
    DecisionTreeError,
    InvalidConditionDefinition,
    InvalidRuntimeValueType,
    InvalidStartNode,
    InvalidTreeStructure,
    LinkNotEnabled,
    LinkTargetNodeNotFound,
    LinkTargetNotFound,
    MissingRuntimePath,
    NoMatchingTransition,
    TraversalCycleDetected,
    TraversalLimitExceeded,
    TreeNotFound,
    UnsupportedOperator,
)
from cdss.domain.decision_tree.graph import (
    EdgeDefinition,
    NodeDefinition,
    SourceReferenceDefinition,
    TreeDefinition,
    TreeGraph,
    TreeGraphRepository,
)
from cdss.domain.decision_tree.patches import ContextPatchResult, apply_context_patch
from cdss.domain.decision_tree.paths import resolve_runtime_path
from cdss.domain.decision_tree.validator import (
    TreeValidationResult,
    TreeValidationWarning,
    validate_tree_graph,
)
from cdss.domain.decision_tree.walker import DEFAULT_MAX_STEPS, walk_tree

__all__ = [
    "ContextPatchError",
    "ContextPatchResult",
    "ConditionEvaluation",
    "collect_action",
    "DecisionTreeError",
    "DEFAULT_MAX_STEPS",
    "EdgeDefinition",
    "ExecutedAction",
    "ExecutedReference",
    "evaluate_candidate_condition",
    "evaluate_condition",
    "FrozenJsonObject",
    "InvalidConditionDefinition",
    "InvalidRuntimeValueType",
    "InvalidStartNode",
    "InvalidTreeStructure",
    "JsonObject",
    "JsonValue",
    "LinkNotEnabled",
    "LinkTargetNodeNotFound",
    "LinkTargetNotFound",
    "MissingRuntimePath",
    "NoMatchingTransition",
    "NodeDefinition",
    "NodeType",
    "RunState",
    "resolve_runtime_path",
    "SourceReferenceDefinition",
    "TraceEvent",
    "TraversalCycleDetected",
    "TraversalLimitExceeded",
    "TraversalResult",
    "TraversalTraceEntry",
    "TreeDefinition",
    "TreeGraph",
    "TreeGraphRepository",
    "TreeMetadata",
    "TreeNotFound",
    "TreeValidationResult",
    "TreeValidationWarning",
    "UnsupportedOperator",
    "apply_context_patch",
    "validate_condition_definition",
    "validate_tree_graph",
    "walk_tree",
]
