"""Medicine lookup data, generated from backups/medicines.sql.

GENERATED FILE -- do not hand-edit. To change a dose, name, or
availability: edit backups/medicines.sql, then regenerate:

    uv run python backups/generate_medicines.py
"""

from __future__ import annotations

from collections.abc import Mapping

from cdss.domain.decision_tree.contracts import JsonObject

MEDICINES: tuple[JsonObject, ...] = (
    {
        "drug_id": "DRUG0001",
        "name": "Diltiazem",
        "drug_class": "C",
        "subgroup": "CKCa Non-DHP",
        "route": "Thuốc Uống",
        "dose_low": "120 mg",
        "dose_usual": "180 - 240 mg",
        "dose_max": "240 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0002",
        "name": "Verapamil",
        "drug_class": "C",
        "subgroup": "CKCa Non-DHP",
        "route": "Thuốc Uống",
        "dose_low": "120 mg",
        "dose_usual": "240 - 360 mg",
        "dose_max": "360 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0003",
        "name": "Amlodipine",
        "drug_class": "C",
        "subgroup": "CKCa DHP",
        "route": "Thuốc Uống",
        "dose_low": "2.5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0004",
        "name": "Felodipine",
        "drug_class": "C",
        "subgroup": "CKCa DHP",
        "route": "Thuốc Uống",
        "dose_low": "2.5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0005",
        "name": "Isradipine",
        "drug_class": "C",
        "subgroup": "CKCa DHP",
        "route": "Thuốc Uống",
        "dose_low": "2.5 mg BID",
        "dose_usual": "5 - 10 mg BID",
        "dose_max": "20 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0006",
        "name": "Nifedipine",
        "drug_class": "C",
        "subgroup": "CKCa DHP",
        "route": "Thuốc Uống",
        "dose_low": "30 mg",
        "dose_usual": "30 - 90 mg",
        "dose_max": "90 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0007",
        "name": "Nitrendipine",
        "drug_class": "C",
        "subgroup": "CKCa DHP",
        "route": "Thuốc Uống",
        "dose_low": "10 mg",
        "dose_usual": "20 mg",
        "dose_max": "20 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0008",
        "name": "Lercanidipine",
        "drug_class": "C",
        "subgroup": "CKCa DHP",
        "route": "Thuốc Uống",
        "dose_low": "10 mg",
        "dose_usual": "20 mg",
        "dose_max": "20 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0009",
        "name": "Benazepril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "5 mg",
        "dose_usual": "10 - 40 mg",
        "dose_max": "40 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0010",
        "name": "Captopril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "12.5 mg BID",
        "dose_usual": "50 - 100 mg BID",
        "dose_max": "200 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0011",
        "name": "Enalapril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "5 mg",
        "dose_usual": "10 - 40 mg",
        "dose_max": "40 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0012",
        "name": "Fosinopril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "10 mg",
        "dose_usual": "10 - 40 mg",
        "dose_max": "40 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0013",
        "name": "Lisinopril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "5 mg",
        "dose_usual": "10 - 40 mg",
        "dose_max": "40 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0014",
        "name": "Perindopril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "3.5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0015",
        "name": "Quinapril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "5 mg",
        "dose_usual": "10 - 40 mg",
        "dose_max": "40 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0016",
        "name": "Ramipril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "2.5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0017",
        "name": "Trandolapril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "1 - 2 mg",
        "dose_usual": "2 - 8 mg",
        "dose_max": "8 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0018",
        "name": "Imidapril",
        "drug_class": "A",
        "subgroup": "ƯCMC",
        "route": "Thuốc Uống",
        "dose_low": "2.5 - 5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0019",
        "name": "Azilsartan",
        "drug_class": "A",
        "subgroup": "CTTA",
        "route": "Thuốc Uống",
        "dose_low": "40 mg",
        "dose_usual": "80 mg",
        "dose_max": "80 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0020",
        "name": "Candesartan",
        "drug_class": "A",
        "subgroup": "CTTA",
        "route": "Thuốc Uống",
        "dose_low": "4 mg",
        "dose_usual": "8 - 32 mg",
        "dose_max": "32 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0021",
        "name": "Eprosartan",
        "drug_class": "A",
        "subgroup": "CTTA",
        "route": "Thuốc Uống",
        "dose_low": "400 mg",
        "dose_usual": "600 - 800 mg",
        "dose_max": "800 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0022",
        "name": "Irbesartan",
        "drug_class": "A",
        "subgroup": "CTTA",
        "route": "Thuốc Uống",
        "dose_low": "150 mg",
        "dose_usual": "150 - 300 mg",
        "dose_max": "300 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0023",
        "name": "Losartan",
        "drug_class": "A",
        "subgroup": "CTTA",
        "route": "Thuốc Uống",
        "dose_low": "50 mg",
        "dose_usual": "50 - 100 mg",
        "dose_max": "100 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0024",
        "name": "Olmesartan",
        "drug_class": "A",
        "subgroup": "CTTA",
        "route": "Thuốc Uống",
        "dose_low": "10 mg",
        "dose_usual": "20 - 40 mg",
        "dose_max": "40 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0025",
        "name": "Telmisartan",
        "drug_class": "A",
        "subgroup": "CTTA",
        "route": "Thuốc Uống",
        "dose_low": "40 mg",
        "dose_usual": "40 - 80 mg",
        "dose_max": "80 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0026",
        "name": "Valsartan",
        "drug_class": "A",
        "subgroup": "CTTA",
        "route": "Thuốc Uống",
        "dose_low": "80 mg",
        "dose_usual": "80 - 320 mg",
        "dose_max": "320 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0027",
        "name": "Bendroflumethiazide",
        "drug_class": "D",
        "subgroup": "LT Thiazide",
        "route": "Thuốc Uống",
        "dose_low": "5 mg",
        "dose_usual": "10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0028",
        "name": "Chlorthalidone",
        "drug_class": "D",
        "subgroup": "LT Thiazide-like",
        "route": "Thuốc Uống",
        "dose_low": "12.5 mg",
        "dose_usual": "12.5 - 25 mg",
        "dose_max": "25 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0029",
        "name": "Hydrochlorothiazide",
        "drug_class": "D",
        "subgroup": "LT Thiazide",
        "route": "Thuốc Uống",
        "dose_low": "12.5 mg",
        "dose_usual": "12.5 - 50 mg",
        "dose_max": "50 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0030",
        "name": "Indapamide",
        "drug_class": "D",
        "subgroup": "LT Thiazide-like",
        "route": "Thuốc Uống",
        "dose_low": "1.25 mg",
        "dose_usual": "2.5 mg",
        "dose_max": "2.5 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0031",
        "name": "Bumetanide",
        "drug_class": "D",
        "subgroup": "LT quai",
        "route": "Thuốc Uống",
        "dose_low": "0.5 mg",
        "dose_usual": "1 mg",
        "dose_max": "1 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0032",
        "name": "Furosemide",
        "drug_class": "D",
        "subgroup": "LT quai",
        "route": "Thuốc Uống/Thuốc Truyền Tĩnh Mạch",
        "dose_low": "20 mg BID",
        "dose_usual": "40 mg BID",
        "dose_max": "Variable",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0033",
        "name": "Torsemide",
        "drug_class": "D",
        "subgroup": "LT quai",
        "route": "Thuốc Uống",
        "dose_low": "5 mg",
        "dose_usual": "10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0034",
        "name": "Amiloride",
        "drug_class": "D",
        "subgroup": "LT giữ Kali",
        "route": "Thuốc Uống",
        "dose_low": "5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0035",
        "name": "Eplerenone",
        "drug_class": "D",
        "subgroup": "LT giữ Kali (MRA)",
        "route": "Thuốc Uống",
        "dose_low": "25 mg",
        "dose_usual": "50 - 100 mg",
        "dose_max": "100 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0036",
        "name": "Spironolactone",
        "drug_class": "D",
        "subgroup": "LT giữ Kali (MRA)",
        "route": "Thuốc Uống",
        "dose_low": "12.5 mg",
        "dose_usual": "25 - 50 mg",
        "dose_max": "50 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0037",
        "name": "Triamterene",
        "drug_class": "D",
        "subgroup": "LT giữ Kali",
        "route": "Thuốc Uống",
        "dose_low": "100 mg",
        "dose_usual": "100 mg",
        "dose_max": "100 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0038",
        "name": "Acebutolol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "200 mg",
        "dose_usual": "200 - 400 mg",
        "dose_max": "400 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0039",
        "name": "Atenolol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "25 mg",
        "dose_usual": "100 mg",
        "dose_max": "100 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0040",
        "name": "Bisoprolol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0041",
        "name": "Carvedilol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "3.125 mg BID",
        "dose_usual": "6.25 - 25 mg BID",
        "dose_max": "50 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0042",
        "name": "Labetalol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống/Thuốc Truyền Tĩnh Mạch",
        "dose_low": "100 mg BID",
        "dose_usual": "100 - 300 mg BID",
        "dose_max": "600 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0043",
        "name": "Metoprolol Succinate",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "25 mg",
        "dose_usual": "50 - 100 mg",
        "dose_max": "100 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0044",
        "name": "Metoprolol Tartrate",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "25 mg BID",
        "dose_usual": "50 - 100 mg BID",
        "dose_max": "200 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0045",
        "name": "Nadolol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "20 mg",
        "dose_usual": "40 - 80 mg",
        "dose_max": "80 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0046",
        "name": "Nebivolol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "2.5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0047",
        "name": "Propranolol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Uống",
        "dose_low": "40 mg BID",
        "dose_usual": "40 - 160 mg BID",
        "dose_max": "320 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0048",
        "name": "Aliskiren",
        "drug_class": None,
        "subgroup": "Ức chế Renin trực tiếp",
        "route": "Thuốc Uống",
        "dose_low": "75 mg",
        "dose_usual": "150 - 300 mg",
        "dose_max": "300 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0049",
        "name": "Doxazosin",
        "drug_class": None,
        "subgroup": "Ức chế thụ thể Alpha giao cảm",
        "route": "Thuốc Uống",
        "dose_low": "1 mg",
        "dose_usual": "1 - 2 mg",
        "dose_max": "2 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0050",
        "name": "Prazosin",
        "drug_class": None,
        "subgroup": "Ức chế thụ thể Alpha giao cảm",
        "route": "Thuốc Uống",
        "dose_low": "1 mg BID",
        "dose_usual": "1 - 5 mg BID",
        "dose_max": "10 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0051",
        "name": "Terazosin",
        "drug_class": None,
        "subgroup": "Ức chế thụ thể Alpha giao cảm",
        "route": "Thuốc Uống",
        "dose_low": "1 mg",
        "dose_usual": "1 - 2 mg",
        "dose_max": "2 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0052",
        "name": "Hydralazine",
        "drug_class": None,
        "subgroup": "Giãn mạch",
        "route": "Thuốc Uống/Thuốc Truyền Tĩnh Mạch",
        "dose_low": "10 mg BID",
        "dose_usual": "25 - 100 mg BID",
        "dose_max": "200 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0053",
        "name": "Minoxidil",
        "drug_class": None,
        "subgroup": "Giãn mạch",
        "route": "Thuốc Uống",
        "dose_low": "2.5 mg",
        "dose_usual": "5 - 10 mg",
        "dose_max": "10 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0054",
        "name": "Clonidine",
        "drug_class": None,
        "subgroup": "Chủ vận chọn lọc alpha-2 giao cảm",
        "route": "Thuốc Uống",
        "dose_low": "0.1 mg BID",
        "dose_usual": "0.1 - 0.2 mg BID",
        "dose_max": "0.4 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0055",
        "name": "Methyldopa",
        "drug_class": None,
        "subgroup": "Chủ vận chọn lọc alpha-2 giao cảm",
        "route": "Thuốc Uống",
        "dose_low": "125 mg BID",
        "dose_usual": "250 - 500 mg BID",
        "dose_max": "1000 mg/ngày",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0056",
        "name": "Reserpine",
        "drug_class": None,
        "subgroup": "Giảm Adrenergic",
        "route": "Thuốc Uống",
        "dose_low": "0.1 mg",
        "dose_usual": "0.1 - 0.25 mg",
        "dose_max": "0.25 mg",
        "source": "Bảng 10",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0057",
        "name": "Nicardipine",
        "drug_class": "C",
        "subgroup": "CKCa DHP",
        "route": "Thuốc Truyền Tĩnh Mạch",
        "dose_low": "3 mg/giờ",
        "dose_usual": "5 mg/giờ",
        "dose_max": "15 mg/giờ",
        "source": "Mục 3.7.5",
        "link": "https://drugs.com/dosage/nicardipine.html",
        "available": True,
    },
    {
        "drug_id": "DRUG0058",
        "name": "Clevidipine",
        "drug_class": "C",
        "subgroup": "CKCa DHP",
        "route": "Thuốc Truyền Tĩnh Mạch",
        "dose_low": "1 - 2 mg/giờ",
        "dose_usual": "4 - 6 mg/giờ",
        "dose_max": "16-32 mg/giờ",
        "source": "Mục 3.7.5",
        "link": "https://drugs.com/dosage/clevidipine.html",
        "available": True,
    },
    {
        "drug_id": "DRUG0059",
        "name": "Esmolol",
        "drug_class": "B",
        "subgroup": "CB",
        "route": "Thuốc Truyền Tĩnh Mạch",
        "dose_low": "50 mcg/kg/phút",
        "dose_usual": "50-250 mcg/kg/phút",
        "dose_max": "300 mcg/kg/phút",
        "source": "Mục 3.7.5",
        "link": "https://drugs.com/dosage/esmolol.html",
        "available": True,
    },
    {
        "drug_id": "DRUG0060",
        "name": "Nitroprusside",
        "drug_class": None,
        "subgroup": "Giãn mạch",
        "route": "Thuốc Truyền Tĩnh Mạch",
        "dose_low": "0.3 mcg/kg/phút",
        "dose_usual": "0.3-10 mcg/kg/phút",
        "dose_max": "10 mcg/kg/phút",
        "source": "Mục 3.7.5",
        "link": "https://drugs.com/dosage/nitroprusside.html",
        "available": True,
    },
    {
        "drug_id": "DRUG0061",
        "name": "Nitroglycerin",
        "drug_class": None,
        "subgroup": "Giãn mạch",
        "route": "Thuốc Truyền Tĩnh Mạch",
        "dose_low": "5 mcg/phút",
        "dose_usual": "10 mcg/phút",
        "dose_max": "20 mcg/phút",
        "source": "Mục 3.7.5",
        "link": "https://drugs.com/dosage/nitroglycerin.html",
        "available": True,
    },
    {
        "drug_id": "DRUG0062",
        "name": "Dapagliflozin",
        "drug_class": "SGLT2i",
        "subgroup": "SGLT2i",
        "route": "Thuốc Uống",
        "dose_low": "5-10 mg",
        "dose_usual": "10 mg",
        "dose_max": "10 mg",
        "source": "Mục 3.7.1",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0063",
        "name": "Empagliflozin",
        "drug_class": "SGLT2i",
        "subgroup": "SGLT2i",
        "route": "Thuốc Uống",
        "dose_low": "10 mg",
        "dose_usual": "10 mg",
        "dose_max": "25 mg",
        "source": "Mục 3.7.1",
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0064",
        "name": "Urapidil",
        "drug_class": None,
        "subgroup": "Ức chế thụ thể Alpha giao cảm",
        "route": "Thuốc Uống/Thuốc Truyền Tĩnh Mạch",
        "dose_low": None,
        "dose_usual": None,
        "dose_max": None,
        "source": None,
        "link": None,
        "available": True,
    },
    {
        "drug_id": "DRUG0065",
        "name": "Aspirin",
        "drug_class": None,
        "subgroup": None,
        "route": None,
        "dose_low": "75 - 81 mg/ngày",
        "dose_usual": None,
        "dose_max": "150 - 162 mg/ngày",
        "source": None,
        "link": "https://www.drugs.com/pregnancy/aspirin.html ; https://www.drugs.com/dosage/aspirin.html",
        "available": True,
    },
)

MEDICINES_BY_ID: Mapping[str, JsonObject] = {
    str(medicine["drug_id"]): medicine for medicine in MEDICINES
}

_CLASS_LETTERS = sorted({str(m["drug_class"]) for m in MEDICINES if m["drug_class"] is not None})

MEDICINES_BY_CLASS: Mapping[str, tuple[JsonObject, ...]] = {
    class_letter: tuple(m for m in MEDICINES if m["drug_class"] == class_letter)
    for class_letter in _CLASS_LETTERS
}
